(1, 'Muse', 'Butterflies and Hurricanes (Intro Version)', 'Need for Speed', 'Most Wanted (2012)', 'fwIbuh4M9D4', 'Only during intro cutscene and driving to the first car.'),
(2, 'The Who', 'Baba O\'Riley (Alan Wilkis Remix)', 'Need for Speed', 'Most Wanted (2012)', 'ikb33cQ9D5E', 'First race (in intro)'),
(3, 'The Who', 'Won\'t Get Fooled Again (Cato Remix)', 'Need for Speed', 'Most Wanted (2012)', 'CRd_twtmrPg', ''),
(4, 'Calvin Harris', 'We\'ll Be Coming Back (KillSonik Remix)', 'Need for Speed', 'Most Wanted (2012)', 'BIbJStRXlN8', 'Gamescom Gameplay'),
(5, 'Dizzee Rascal', 'Bonkers', 'Need for Speed', 'Most Wanted (2012)', 'UCkhqNQY5KI', 'Get Wanted Trailer'),
(6, 'Adam Freeland', 'Mind Killer (Jagz Kooner Remix)', 'Need for Speed', 'Underground 2', 'JnU5vCpbJwA', ''),
(7, 'Christopher Lawrence', 'Rush Hour', 'Need for Speed', 'Underground 2', 'f11aEVOKHts', ''),
(8, 'Cirrus', 'Back On A Mission', 'Need for Speed', 'Underground 2', 'HuO0Rk-cRio', 'Jackson Heights cutscene.'),
(9, 'Felix Da Housecat', 'Rocket Ride (Soulwax Remix)', 'Need for Speed', 'Underground 2', 'geN1LP6HMvY', ''),
(10, 'Fluke', 'Switch/Twitch', 'Need for Speed', 'Underground 2', 'Awaph0MavCw', 'Appeared in demo version (PS2). First trailer. Downhill Drift cutscene.'),
(11, 'Madeon', 'The City (feat. Zak Waters)', 'Need for Speed', 'Most Wanted (2012)', 'DbwmgRrXUWA', ''),
(12, 'Muse', 'Butterflies and Hurricanes (Album Version)', 'Need for Speed', 'Most Wanted (2012)', 'EzCKrwOme2U', ''),
(13, 'Helmet', 'Crashing Foreign Cars', 'Need for Speed', 'Underground 2', 'meceOI5LrG4', ''),
(14, 'Killradio', 'Scavenger', 'Need for Speed', 'Underground 2', '2HpEM7AaDRg', ''),
(15, 'Skrillex (with The Doors)', 'Breakn\' a Sweat (Zedd Remix)', 'Need for Speed', 'Most Wanted (2012)', 'BXd26fXFXhM', ''),
(16, 'Nero', 'Won\'t You (Be There)', 'Need for Speed', 'Most Wanted (2012)', 'YYuSfi6j2E8', 'Played in cutscene after defeating final Most Wanted racer.'),
(17, 'Rudimental', 'Feel The Love (feat. John Newman)', 'Need for Speed', 'Most Wanted (2012)', '6tJTgKxmdDs', 'Wii U Trailer '),
(18, 'Killing Joke', 'The Death & Resurrection Show', 'Need for Speed', 'Underground 2', 'oY5wcVRsptM', ''),
(19, 'Silent Code', 'Night Train', 'Need for Speed', 'Most Wanted (2012)', '6e-nb9rCz64', ''),
(20, 'Ministry', 'No W', 'Need for Speed', 'Underground 2', 'pR3ElHmOgA4', ''),
(21, 'Silent Code', 'Spell Bound', 'Need for Speed', 'Most Wanted (2012)', 'T13Pann2oJg', ''),
(22, 'Silent Code', 'East Star', 'Need for Speed', 'Most Wanted (2012)', 'wuwquKSKpdg', ''),
(23, 'The Maccabees', 'Unknow', 'Need for Speed', 'Most Wanted (2012)', 'TzDwHfWsPzo', 'Demo Trailer'),
(24, 'Mudvayne', 'Determined', 'Need for Speed', 'Underground 2', '32tqV-6nahQ', ''),
(25, 'The Joy Formidable', 'Little Blimp', 'Need for Speed', 'Most Wanted (2012)', 'RtghKWVU9AY', ''),
(26, 'Foreign Beggars', 'Contact (feat. Noisia)', 'Need for Speed', 'Most Wanted (2012)', 'XJp0oWhgJEU', ''),
(27, 'Flux Pavilion', 'Double Edge (feat. Sway & P Money)', 'Need for Speed', 'Most Wanted (2012)', 'VNO4K6S0nu4', ''),
(28, 'The Chemical Brothers', 'Galvanize', 'Need for Speed', 'Most Wanted (2012)', 'qat3Je5fLMw', ''),
(29, 'Paul Van Dyk', 'Nothing But You (Cirrus Remix)', 'Need for Speed', 'Underground 2', 'RmJCKRJx9Dc', 'Appeared in demo version (PC).'),
(30, 'Riverboat Gamblers', 'Blue Ghosts', 'Need for Speed', 'Most Wanted (2012)', 'TaZp1538ShI', 'DLC Trailer: Ultimate Speed Pack; Play Your Own Way '),
(31, 'Green Day', 'Stop When The Red Lights Flash', 'Need for Speed', 'Most Wanted (2012)', 'Vg61SGjUcGE', ''),
(32, 'Icona Pop', 'I Love It', 'Need for Speed', 'Most Wanted (2012)', 'l5qOTyXC9cA', ''),
(33, 'X Ambassadors', 'Unconsolable', 'Need for Speed', 'Most Wanted (2012)', '2a4Dhh2YFkA', ''),
(34, 'Dispatch', 'Circles Around The Sun', 'Need for Speed', 'Most Wanted (2012)', 'CKRX-R6yVDs', ''),
(35, 'We Are The Ocean', 'The Road (Run For Miles)', 'Need for Speed', 'Most Wanted (2012)', 'pSOV7zlussg', ''),
(36, 'Queens of the Stone Age', 'In My Head', 'Need for Speed', 'Underground 2', '8a8PonO1bl0', 'Appeared in demo version (PC).'),
(37, 'DJ Fresh', 'The Power (feat. Dizzee Rascal)', 'Need for Speed', 'Most Wanted (2012)', '1OGECxAMOts', ''),
(38, 'RuN RIOT', 'A Light Goes Off (RuN RIOT Mix)', 'Need for Speed', 'Most Wanted (2012)', 'bU1AyOXffzA', ''),
(40, 'Deadmau5', 'Channel 42 (feat. Wolfgang Gartner)', 'Need for Speed', 'Most Wanted (2012)', 'EKcOeDEzM-I', ''),
(41, 'Above & Beyond', 'Anjunabeach', 'Need for Speed', 'Most Wanted (2012)', 'tO7JDc_JkJ4', ''),
(42, 'The Vaccines', 'Bad Mood', 'Need for Speed', 'Most Wanted (2012)', '4-Y14OUD2tw', ''),
(43, 'C&D', 'The Chase', 'Need for Speed', 'Most Wanted (2012)', 'KEnzjCUgwcA', 'Deluxe DLC Bundle Trailer '),
(44, 'Poliça', 'Violent Games', 'Need for Speed', 'Most Wanted (2012)', 'D298isUQF-w', ''),
(45, 'Bassnectar', 'Empathy', 'Need for Speed', 'Most Wanted (2012)', 'oRH6Rj2eVlo', 'Deluxe DLC Bundle Trailer; Mobile Trailer; EA Presents: The Most Wanted Taxi In Sydney'),
(46, 'Crosses', 'Telepathy', 'Need for Speed', 'Most Wanted (2012)', 'SO1dMYmCTJc', 'Second intro cutscene (chases; security gates etc.)'),
(47, 'Beware of Darkness', 'Howl', 'Need for Speed', 'Most Wanted (2012)', 'jetYoOMbvD8', ''),
(48, 'Lower than Atlantis', 'Love Someone Else', 'Need for Speed', 'Most Wanted (2012)', 'g_-buIx-5Fs', ''),
(49, 'Strange Talk', 'Cast Away', 'Need for Speed', 'Most Wanted (2012)', 'nRPN56RRTdU', ''),
(50, 'Last Dinosaurs', 'Zoom', 'Need for Speed', 'Most Wanted (2012)', '6wWdmwsYbZM', ''),
(51, 'Asherel', 'Shake The Dust', 'Need for Speed', 'Most Wanted (2012)', 'K0aWHWOpqPs', ''),
(52, 'Band of Skulls', 'You\'re Not Pretty But You Got It Goin\' On', 'Need for Speed', 'Most Wanted (2012)', 'ykuRcfR2KJQ', ''),
(53, 'Dead Sara', 'Weatherman', 'Need for Speed', 'Most Wanted (2012)', '4DLGmRF1Go4', 'Played in credits.'),
(54, 'Popeska', 'Now or Never (Gartner Edit)', 'Need for Speed', 'Most Wanted (2012)', 'BsJ6IORCV0Y', 'Deluxe DLC Bundle Trailer '),
(55, 'MuteMath', 'Allies', 'Need for Speed', 'Most Wanted (2012)', 'EnYPjfuaziY', ''),
(56, 'The Prodigy', 'Firestarter', 'Need for Speed', 'Most Wanted (2012)', 'FCt6xbd3vB4', 'E3 Trailer'),
(57, 'Mick Gordon', 'Baba O\'Riley (Most Wanted Remix)', 'Need for Speed', 'Most Wanted (2012)', 'nhGGisFB0cw', 'Multiplayer Trailer'),
(60, 'Heaven\'s Basement', 'I Am Electric', 'Need for Speed', 'Most Wanted (2012)', '0jdRIanSYPM', 'Launch Trailer'),
(61, 'Rise Against', 'Give It All', 'Need for Speed', 'Underground 2', 'dhldbymXK-8', ''),
(62, 'Septembre', 'I Am Weightless', 'Need for Speed', 'Underground 2', 'Qanjyp2xOCk', ''),
(63, 'Skindred', 'Nobody', 'Need for Speed', 'Underground 2', 'wPW5b2rPn3M', ''),
(64, 'Sin', 'Hard EBM', 'Need for Speed', 'Underground 2', 'Jl-G5DHOWSw', ''),
(65, 'Snapcase', 'Skeptic', 'Need for Speed', 'Underground 2', 'gQZy6YAlJx0', ''),
(66, 'Sonic Animation', 'E-Ville', 'Need for Speed', 'Underground 2', 'kb171cHdS1c', '\"Cast\" Trailer (#7).'),
(67, 'Spiderbait', 'Black Betty', 'Need for Speed', 'Underground 2', 'ckPfk3Lu8PU', 'E3 2004 Trailer'),
(68, 'The Bronx', 'Notice of Eviction', 'Need for Speed', 'Underground 2', 'sx07QQnJQqI', 'Appeared in demo version (PS2).'),
(69, 'Unwritten Law', 'The Celebration Song', 'Need for Speed', 'Underground 2', '8x8zPoYRRbQ', ''),
(70, 'Capone', 'I Need Speed', 'Need for Speed', 'Underground 2', 'oM9WvXWyYxo', ''),
(71, 'Chingy', 'I Do', 'Need for Speed', 'Underground 2', 'UKMARi4HDSw', 'Appeared in demo version (PC). \"Cast\" Trailer (#7).'),
(72, 'Snoop Dogg', 'Riders On The Storm feat. The Doors (Fredwreck Remix)', 'Need for Speed', 'Underground 2', '08Blnwor5Hc', 'Always played after intro. \"NFSU2 Launch Event\" trailer.'),
(73, 'Terror Squad', 'Lean Back', 'Need for Speed', 'Underground 2', 'r1UhPz_73cY', '\"Spinners\" trailer (#15).'),
(74, 'Xzibit', 'LAX', 'Need for Speed', 'Underground 2', 'hdOLGBGjpxA', 'Coal Harbor West cutscene.'),
(75, 'Sly Boogy', 'That\'z My Name', 'Need for Speed', 'Underground 2', 'dyXBkPfj0IU', ''),
(76, 'Jeff Dyck', 'Chronos', 'Road & Track Presents:', 'The Need for Speed', 'COkc6ubMQ8c', ''),
(77, 'Jeff Dyck', 'Funkn Bubba', 'Road & Track Presents:', 'The Need for Speed', 'dHDSCxIJBRs', ''),
(78, 'Jeff Dyck', 'Hideous', 'Road & Track Presents:', 'The Need for Speed', 'fpgWxX5zCCE', ''),
(79, 'Jeff Dyck & Angela Somerville', 'Aaeeyaaeeyaa', 'Road & Track Presents:', 'The Need for Speed', '7gr8JpDNyME', ''),
(80, 'Jeff Dyck', 'Odyssey', 'Road & Track Presents:', 'The Need for Speed', 'j1aPdPq6AHo', ''),
(81, 'Jeff Dyck', 'Fill\'er Up', 'Road & Track Presents:', 'The Need for Speed', 'O3dRKnoffls', ''),
(82, 'Saki Kaskas', 'Route 99', 'Road & Track Presents:', 'The Need for Speed', 'Q1j-r5Jc6jE', ''),
(83, 'Saki Kaskas', 'Overheated', 'Road & Track Presents:', 'The Need for Speed', 'rp78S8ngppw', ''),
(84, 'Saki Kaskas', 'Scud', 'Road & Track Presents:', 'The Need for Speed', '6q-E7rtFBmc', ''),
(85, 'Saki Kaskas', 'Toxic Exhaust', 'Road & Track Presents:', 'The Need for Speed', 'by9BiO6f85U', ''),
(86, 'Saki Kaskas', 'Rampant', 'Road & Track Presents:', 'The Need for Speed', 'Wh0OZqUr7v4', ''),
(87, 'Jeff Dyck & Saki Kaskas', 'Pause Screen Theme', 'Road & Track Presents:', 'The Need for Speed', 'ToIdQuDz3CI', 'Played in menu'),
(89, 'Alistair Hirst', 'Menu Theme - Power Slide', 'Road & Track Presents:', 'The Need for Speed', 'D9FLsZvAMjY', 'Played in menu'),
(90, 'Jeff Dyck & Saki Kaskas', 'Fasolatha', '', 'Need for Speed II', 'OVu8EZf00vI', ''),
(91, 'Jeff Dyck & Saki Kaskas', 'Headless Horse', '', 'Need for Speed II', '3wS32T_YsyQ', ''),
(92, 'Jeff Dyck & Saki Kaskas', 'Nashat', '', 'Need for Speed II', 'MSA6l_0LbVo', ''),
(93, 'Jeff Dyck & Saki Kaskas', 'Gore', '', 'Need for Speed II', '8nbCDdkbVHo', ''),
(94, 'Robert Ridihalgh', 'Halling Ass', '', 'Need for Speed II', '9RTO4qPEm64', ''),
(95, 'Jeff Dyck', 'Corroboree', '', 'Need for Speed II', 'fhvfRdxsWrg', ''),
(96, 'Jeff Dyck', 'Pavlova', '', 'Need for Speed II', 'PKw10-JCgEE', ''),
(97, 'Jeff Dyck', 'Heinerklingle', '', 'Need for Speed II', 'QR5HgiQceJk', ''),
(98, 'Robert Ridihalgh', 'Angry Ghosts', '', 'Need for Speed II', '-vExrfVyKHg', 'Special Edition exclusive'),
(99, 'Alistair Hirst', 'Refried Jumping Beans', '', 'Need for Speed II', 'Q5FSaMiwmP8', 'Special Edition exclusive'),
(100, 'Rom Di Prisco', 'Ferrari F355', '', 'Need for Speed II', 'TPfgIB2-tgA', 'Special Edition exclusive'),
(101, 'Robert Ridihalgh', 'Ford Mustang Mach III', '', 'Need for Speed II', 'wSzusDiSE6I', 'Special Edition exclusive'),
(102, 'Rom Di Prisco & Saki Kaskas', 'Italdesign Nazca C2', '', 'Need for Speed II', 'Dn4EzlznRoU', 'Special Edition exclusive'),
(103, 'Saki Kaskas', 'Siwash Rock', '', 'Need for Speed II', 'y8RXp03wxRY', ''),
(104, 'Saki Kaskas', 'Sanoqoua', '', 'Need for Speed II', 'iSCU9Bn-0S8', ''),
(105, 'Saki Kaskas', 'Feta Cheese', '', 'Need for Speed II', 'ZVhzILRybKQ', ''),
(106, 'Alistair Hirst', 'Hell Bent For Lederhosen', '', 'Need for Speed II', 'QvMimQ9YD1Y', ''),
(107, 'Alistair Hirst', 'Kangchenjunga', '', 'Need for Speed II', 'rgKCzH14zjA', ''),
(108, 'Jay Weinland', 'Sound Stage Strut', '', 'Need for Speed II', 'rIthk5muJK0', ''),
(109, 'Rom Di Prisco', 'Main Menu', '', 'Need for Speed II', '69-J2m_GyhI', ''),
(110, 'Rom Di Prisco', 'Romulus 3', '', 'Need for Speed II', 'uBO_366ngIc', 'Showroom Music'),
(111, 'Rom Di Prisco', 'Lotus Esprit V8', '', 'Need for Speed II', 'r_6ulg8_Ktw', ''),
(112, 'Rom Di Prisco', 'McLaren F1', '', 'Need for Speed II', 'tl1_WFB8eOg', ''),
(113, 'Rom Di Prisco & Saki Kaskas', 'Lotus Elise GT1', '', 'Need for Speed II', '-6_XCL-iJ9M', ''),
(114, 'Koko Productions', 'Italdesign Calá', '', 'Need for Speed II', 'foho9d0JZt4', ''),
(115, 'Koko Productions', 'Ford GT90', '', 'Need for Speed II', 'Ov8AQ-X8pAI', ''),
(116, 'Saki Kaskas & Koko Productions', 'Jaguar XJ220', '', 'Need for Speed II', 'HV3Bh_BRjxI', ''),
(117, 'Crispin Hands', 'Cerebral Plumbing', '', 'Need for Speed II', 'MSXpkLfR8Mc', ''),
(118, 'Saki Kaskas', 'Little Sweaty Sow', 'Need for Speed', 'III: Hot Pursuit', 'nmWw10erNKY', ''),
(119, 'Saki Kaskas', 'Knossos', 'Need for Speed', 'III: Hot Pursuit', '39xggE3eEWY', ''),
(120, 'Saki Kaskas', 'Flimsy', 'Need for Speed', 'III: Hot Pursuit', 'Wlmadn-pIuk', ''),
(121, 'Rom Di Prisco', 'Hydrus 606', 'Need for Speed', 'III: Hot Pursuit', '2UaicKgrrgo', ''),
(122, 'Rom Di Prisco', 'Cetus 808', 'Need for Speed', 'III: Hot Pursuit', 'iqp2tzFCKek', ''),
(123, 'Rom Di Prisco', 'Aquila 303', 'Need for Speed', 'III: Hot Pursuit', '5arFuwxJky8', ''),
(124, 'Rom Di Prisco', 'Romulus 3', 'Need for Speed', 'III: Hot Pursuit', 'ziX_f7rdFD4', ''),
(125, 'Rom Di Prisco', 'Triton', 'Need for Speed', 'III: Hot Pursuit', 'fS25XP-Fqhw', ''),
(126, 'Rom Di Prisco', 'Pi', 'Need for Speed', 'III: Hot Pursuit', '0n1RBDIcJfI', ''),
(127, 'Rom Di Prisco', 'Minotaur', 'Need for Speed', 'III: Hot Pursuit', 'XwoU5wQ0yCc', ''),
(128, 'Rom Di Prisco', 'Sirius 909', 'Need for Speed', 'III: Hot Pursuit', 'o1y6-KgsHYM', ''),
(129, 'Rom Di Prisco', 'Demo 1', 'Need for Speed', 'III: Hot Pursuit', 'YavU7mHxyRk', ''),
(130, 'Rom Di Prisco', 'Demo 3', 'Need for Speed', 'III: Hot Pursuit', 'vnIUoXjsenc', ''),
(131, 'Unknown Artist', 'Demo 2', 'Need for Speed', 'III: Hot Pursuit', '0-1vIR7Vl2k', ''),
(132, 'Crispin Hands', 'Monster', 'Need for Speed', 'III: Hot Pursuit', '82eC27KImEo', ''),
(133, 'Matt Ragan', 'Snorkeling Cactus Weasels', 'Need for Speed', 'III: Hot Pursuit', 'VlJz6htmpMc', ''),
(134, 'Matt Ragan', 'Rear Flutterblast #19', 'Need for Speed', 'III: Hot Pursuit', 'KsfzDAfvJoo', ''),
(135, 'Matt Ragan', 'Snow Bags', 'Need for Speed', 'III: Hot Pursuit', 'uhTe7NPx0p8', ''),
(136, 'Alistair Hirst', 'Warped', 'Need for Speed', 'III: Hot Pursuit', 'Aj5_sGhSyGw', ''),
(137, 'Alistair Hirst', 'Whacked', 'Need for Speed', 'III: Hot Pursuit', '2nhn_XimTas', ''),
(138, 'Alistair Hirst', 'Whipped', 'Need for Speed', 'III: Hot Pursuit', '0gOoAMKxmHE', ''),
(139, 'Morphadron', 'Warm Storage', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'N_fVROeSxwA', ''),
(140, 'Morphadron', 'The UK Sound', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'YbDr2YYIoY0', ''),
(141, 'Morphadron', 'Stealth Run', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'cSQ0R6hlppU', ''),
(142, 'Morphadron', 'Rock This Place', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'nA-0PXol_t4', ''),
(143, 'Morphadron', 'Rezidue', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'CYcvRKTVXEA', 'Also in GBA (Race)'),
(144, 'Morphadron', 'R U Ready', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'x9ecGd9jUeo', 'Porsche Chronicle (PS1)'),
(145, 'Morphadron', 'Dr. Know', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'Gqo8Z7dm2b0', ''),
(146, 'Morphadron', 'Loser', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'cQmzPEwwTC8', 'Also in GBA (Lose Theme)'),
(147, 'Morphadron', 'Let the Music Move You', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'BmTrYUYXaSw', ''),
(148, 'Morphadron', 'Hack the Planet', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'oootXQYrLOM', ''),
(149, 'Morphadron', 'Gimme The Power', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'uSF0NDZUPAM', 'Also in GBA (Win Theme)'),
(150, 'Morphadron', 'Funky Phreakout', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'zEycRI7xhIk', ''),
(151, 'Morphadron', 'Cold Fusion Power', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'CkH2gL1pvEU', 'Also in GBA (Menu)'),
(152, 'Morphadron', 'Activator', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'VPSEQ-5rjjc', ''),
(153, 'Morphadron', 'The Moebus', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'cZh-WT9D9Co', ''),
(154, 'Cypher', 'Twin', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'EyIgGhWwJao', ''),
(155, 'Cypher', 'Orion is Lonely', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'liToBfEJztA', ''),
(156, 'Cypher', 'Injector', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'pSD8sfIR32g', ''),
(157, 'Cypher', 'Aircon', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'm2tdymFPpzQ', ''),
(158, 'Cypher', 'Choose Your Enemy', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'hGhohIdxpiI', ''),
(159, 'Cypher', 'Champion', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'nrnqPuORh24', ''),
(160, 'Captain Ginger', 'Aquadelic', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', 'ufXhJHW2LJk', ''),
(161, 'Captain Ginger', 'Psychonaught', 'Need for Speed', 'Porsche 2000/Porsche Unleashed', '_7bdF0oUWWU', ''),
(162, 'Saki Kaskas', 'Amorphous Being', 'Need for Speed', 'Road Challenge/High Stakes', 'MeNulbsTnbc', ''),
(163, 'Saki Kaskas', 'Callista', 'Need for Speed', 'Road Challenge/High Stakes', 'T3PwqBBZUaE', 'Replay music (PS1); Showroom Theme (PC)'),
(164, 'Saki Kaskas', 'Globular Cluster', 'Need for Speed', 'Road Challenge/High Stakes', 'vJFPbE7xy9s', ''),
(165, 'Rom Di Prisco', 'Rock This', 'Need for Speed', 'Road Challenge/High Stakes', 'o2wdGz3Rk6c', ''),
(166, 'Rom Di Prisco', 'Liquid Plasma', 'Need for Speed', 'Road Challenge/High Stakes', 'oXQZSQ1uA1U', ''),
(167, 'Rom Di Prisco', 'Bring That Beat Back', 'Need for Speed', 'Road Challenge/High Stakes', 'aUA_MhxLAgg', ''),
(168, 'Rom Di Prisco', 'Road Warrior', 'Need for Speed', 'Road Challenge/High Stakes', 'hvhj-DkgytY', ''),
(169, 'Rom Di Prisco', 'Electro Optik', 'Need for Speed', 'Road Challenge/High Stakes', 'l58s02uhzfY', 'Replay music (PS1)'),
(170, 'Crispin Hands', 'Bionic', 'Need for Speed', 'Road Challenge/High Stakes', 'HOn4oK9gTDQ', ''),
(171, 'Lunatic Calm', 'Roll The Dice', 'Need for Speed', 'Road Challenge/High Stakes', 'ZgmQK1wVPzg', ''),
(172, 'Junkie XL', 'Def Beat', 'Need for Speed', 'Road Challenge/High Stakes', '55MI6oMQZWg', ''),
(173, 'Junkie XL', 'Fight', 'Need for Speed', 'Road Challenge/High Stakes', '6qsDxQIdI90', ''),
(174, 'Junkie XL', 'War', 'Need for Speed', 'Road Challenge/High Stakes', 'nIUgoMtWzlg', 'Trailer'),
(175, 'Junkie XL', 'No Remorse', 'Need for Speed', 'Road Challenge/High Stakes', 'ONIsabbuxNs', ''),
(176, 'Surreal Madrid', 'Insanity Sauce', 'Need for Speed', 'Road Challenge/High Stakes', 'LUhmPJgbAOM', ''),
(177, 'The Experiment', 'Cost of Freedom', 'Need for Speed', 'Road Challenge/High Stakes', 'iRV2CuOlNqg', ''),
(178, 'Dastrix', 'Dude in the Moon (Luna Mix)', 'Need for Speed', 'Road Challenge/High Stakes', 'w1YvmtbHLHM', ''),
(179, 'DJ Icey', 'Clutch', 'Need for Speed', 'Road Challenge/High Stakes', 'CI45fw_JKK4', ''),
(180, 'Dylan Rhymes', 'Naked and Ashamed', 'Need for Speed', 'Road Challenge/High Stakes', '9eaLmvP7WeI', ''),
(181, 'The Funk Lab', 'I am Electro', 'Need for Speed', 'Road Challenge/High Stakes', '3F-ZoXplpi0', ''),
(182, 'Overseer', 'Doomsday', 'Need for Speed', 'Underground', 'Qssbz0_NUfI', 'Also in GBA Version'),
(183, 'Saki Kaskas', 'Bulbular Swirl', 'Need for Speed', 'Road Challenge/High Stakes', 'Y213M8_2gJ0', ''),
(184, 'Rom Di Prisco', 'Cygnus Rift', 'Need for Speed', 'Road Challenge/High Stakes', 'NiiPXuW5jOY', ''),
(185, 'Rom Di Prisco', 'Paradigm Shifter', 'Need for Speed', 'Road Challenge/High Stakes', '2FnD-JKXRVU', ''),
(186, 'Rom Di Prisco', 'Photon Rez', 'Need for Speed', 'Road Challenge/High Stakes', 'oK311jygFy4', ''),
(187, 'Rom Di Prisco', 'Quantum Singularity', 'Need for Speed', 'Road Challenge/High Stakes', 'QoqDAzDpqhg', ''),
(188, 'Rom Di Prisco & Saki Kaskas & Crispin Hands', 'Runnin\'', 'Need for Speed', 'Road Challenge/High Stakes', 'Akf4vQs7R9A', ''),
(189, 'The Crystal Method', 'Born Too Slow', 'Need for Speed', 'Underground', 'DoYQeomsuWk', 'PC Demo'),
(190, 'Rancid', 'Out Of Control', 'Need for Speed', 'Underground', '1NrFaxAIb_o', ''),
(191, 'Rob Zombie', 'Two Lane Blacktop', 'Need for Speed', 'Underground', 'prrACm_l2Fk', '\"Main Drift Event\" trailer (#3). '),
(192, 'BT', 'Kimosabe', 'Need for Speed', 'Underground', '0Fz7p0GECmA', 'Intro. Announcement Trailer. Drag cutscene. Trailer #2. \"Girls\" trailer (#4). '),
(193, 'Alistair Hirst & Matt Ragan', 'A Groove Thang', '', 'Motor City Online', 'hXkd4i31Vac', 'Radio DBOS (Funk)'),
(194, 'Alistair Hirst & Matt Ragan', 'Backseat Funk', '', 'Motor City Online', 'iah_tFSFPeM', 'Radio DBOS (Funk)'),
(195, 'Alistair Hirst & Matt Ragan', 'Big Bad Rat', '', 'Motor City Online', '1XpRC0AYoOU', 'Radio DDMZ (Classic rock)'),
(196, 'Alistair Hirst & Matt Ragan', 'Cowabunga Alley', '', 'Motor City Online', 'Hey6B6x8X-c', 'Radio DCRZ (Surf)'),
(197, 'Alistair Hirst & Matt Ragan', 'Drag King', '', 'Motor City Online', 'wMzSjN0CGGc', 'Radio DDMX (Oldies)'),
(198, 'Alistair Hirst & Matt Ragan', 'Longboard Shuffle', '', 'Motor City Online', 'YsMNUmGZUtw', 'Radio DCRZ (Surf)'),
(199, 'Alistair Hirst & Matt Ragan', 'Packing a Rod', '', 'Motor City Online', 'tBlVgijEvD4', 'Radio DDMX (Oldies)'),
(200, 'Alistair Hirst & Matt Ragan', 'Psychobilly Slugfest', '', 'Motor City Online', 'MHra78rQEU0', 'Radio DDMX (Oldies)'),
(201, 'Alistair Hirst & Matt Ragan', 'Racing 4 Pinks', '', 'Motor City Online', 'sHkNKv0k5T4', 'Radio DDMX (Oldies)'),
(202, 'Alistair Hirst & Matt Ragan', 'Redlining', '', 'Motor City Online', 'c-mslzj3-c4', 'Radio DDMX (Oldies)'),
(203, 'Alistair Hirst & Matt Ragan', 'Road Riot', '', 'Motor City Online', 'kCzdYnG1Kko', 'Radio DDMX (Oldies)'),
(204, 'Alistair Hirst & Matt Ragan', 'T-bird Whine', '', 'Motor City Online', 'VVENn5CnXt8', 'Radio DDMZ (Classic rock)'),
(205, 'Bush', 'The People That We Love', 'Need for Speed', 'Hot Pursuit 2', 'P_wNDvoUFv0', ''),
(206, 'The Buzzhorn', 'Ordinary', 'Need for Speed', 'Hot Pursuit 2', 'xLEjlhyRTb0', ''),
(207, 'Course of Nature', 'Wall of Shame', 'Need for Speed', 'Hot Pursuit 2', 'jHT_CQCmAq0', ''),
(208, 'Hot Action Cop', 'Fever for the Flava', 'Need for Speed', 'Hot Pursuit 2', 'gKaXucyLLB8', ''),
(209, 'Hot Action Cop', 'Goin\' Down on It', 'Need for Speed', 'Hot Pursuit 2', '2zGzVKV6Pmw', 'Intro; Hot Pursuit 2 Advertisement '),
(210, 'Pulse Ultra', 'Build Your Cages', 'Need for Speed', 'Hot Pursuit 2', 'iKv5ys8ZI34', ''),
(211, 'Rush', 'One Little Victory', 'Need for Speed', 'Hot Pursuit 2', 'rMYDuPWHFAo', ''),
(212, 'Uncle Kracker', 'Keep it Comin\'', 'Need for Speed', 'Hot Pursuit 2', 'MSRAv8dLCxo', ''),
(213, 'Matt Ragan', 'Bundle of Clang', 'Need for Speed', 'Hot Pursuit 2', 'P_fa3bf12bs', ''),
(214, 'Matt Ragan', 'Cone of Silence', 'Need for Speed', 'Hot Pursuit 2', 'Cjva-Iezh9E', ''),
(215, 'Matt Ragan', 'Flam Dance', 'Need for Speed', 'Hot Pursuit 2', 'FaIlvmIurvo', ''),
(216, 'The Humble Brothers', 'Black Hole', 'Need for Speed', 'Hot Pursuit 2', 'KcrIVBF0s9g', ''),
(217, 'The Humble Brothers', 'Brake Stand', 'Need for Speed', 'Hot Pursuit 2', 'nIuQS4xfUEU', 'Reward Video.'),
(218, 'The Humble Brothers', 'Sphere', 'Need for Speed', 'Hot Pursuit 2', 'F00XyTBYw9Y', ''),
(219, 'Rom Di Prisco', 'Cykloid', 'Need for Speed', 'Hot Pursuit 2', '2KcsGhRbH1c', ''),
(220, 'Static-X', 'The Only', 'Need for Speed', 'Underground', 'vMCbJB4yNXo', 'Also in GBA Version'),
(221, 'Element Eighty', 'Broken Promises', 'Need for Speed', 'Underground', 'g_wmwazYnrA', '\"Element Eighty\" trailer (#5).'),
(222, 'Asian Dub Foundation', 'Fortress Europe', 'Need for Speed', 'Underground', 'tKNhGtH1nnw', ''),
(223, 'Hotwire', 'Invisible', 'Need for Speed', 'Underground', 'PwT3Zr5DJvM', ''),
(224, 'Story of the Year', 'And The Hero Will Drown', 'Need for Speed', 'Underground', 'VfIdM1z2fvc', ''),
(225, 'Andy Hunter', 'The Wonders of You (feat. Lyle Day)', 'Need for Speed', 'Underground', 'DuBwXgzA46Y', ''),
(226, 'Junkie XL', 'Action Radius', 'Need for Speed', 'Underground', '4EAK8qX1o18', ''),
(227, 'Fuel', 'Quarter', 'Need for Speed', 'Underground', 'IlRv6NHNaWM', ''),
(228, 'Jerk', 'Sucked In', 'Need for Speed', 'Underground', 'GaXbSyB8bLY', 'Also in GBA Version'),
(229, 'Fluke', 'Snapshot', 'Need for Speed', 'Underground', 'J2vJf7yuXhE', ''),
(230, 'Lostprophets', '(To Hell We) Ride', 'Need for Speed', 'Underground', 'N7uz7ftC8HA', ''),
(231, 'Overseer', 'Supermoves', 'Need for Speed', 'Underground', 'VNH6xtQjPjU', 'PS2 Demo Intro'),
(232, 'FC Kahuna', 'Glitterball', 'Need for Speed', 'Underground', 'ZgRfWo_8bFY', ''),
(233, 'Blindside', 'Swallow', 'Need for Speed', 'Underground', '7nqqTpvyJHM', ''),
(234, 'Lil Jon & The Eastside Boyz', 'Get Low', 'Need for Speed', 'Underground', 'WFbRknwbGFQ', 'Always played after intro. About 25% song lyrics were censored. Also in GBA Version'),
(235, 'Mystikal', 'Smashing The Gas (Get Faster)', 'Need for Speed', 'Underground', '53DBM2AU4do', ''),
(236, 'Dilated People', 'Who\'s Who', 'Need for Speed', 'Underground', 'BFuGiu_Q1f4', ''),
(237, 'Nate Dogg', 'Keep It Comin', 'Need for Speed', 'Underground', 'TAl97oJD0bk', '\"Girls\" trailer (#4). '),
(238, 'X-Ecutioners', 'Body Rock', 'Need for Speed', 'Underground', 'DeSlXTCK58M', '\"Girls\" trailer (#4). '),
(239, 'Petey Pablo', 'Need For Speed', 'Need for Speed', 'Underground', 'RxOyINV8Fes', 'Drift cutscene.'),
(240, 'T.I.', '24\'s', 'Need for Speed', 'Underground', 'yQq2Hm4IO4w', ''),
(241, 'The Black Keys', 'Lonely Boy', 'Need for Speed', 'The Run', 'a_426RiwST8', 'Stage 9 - State Forest'),
(242, 'Black Lips', 'The Lie', 'Need for Speed', 'The Run', 'VGw_E_Z9TmU', ''),
(243, 'Black Pistol Fire', 'Trigger On My FIre', 'Need for Speed', 'The Run', '0GDmOEjMPw8', ''),
(244, 'The Brian Jonestown Massacre', 'The Way It Was', 'Need for Speed', 'The Run', 'KHHYU6IVa7o', ''),
(245, 'Black Rebel Motorcycle Club', 'Beat The Devil\'s Tattoo', 'Need for Speed', 'The Run', 'gn9C1vKd7Gc', 'Stage 8 - The Great Lakes'),
(246, 'Canned Heat', 'On The Road Again', 'Need for Speed', 'The Run', 'qRKNw477onU', 'Stage 6 - The Plains'),
(247, 'Dan Auerbach', 'Heartbroken In Disrepair', 'Need for Speed', 'The Run', '9o4l10CtN7g', 'Stage 1 - West Coast'),
(248, 'The Dead Weather', 'Treat Me Like Your Mother', 'Need for Speed', 'The Run', '5k1p6aD3k1E', 'Stage 2 - National Park'),
(249, 'Donovan', 'Riki Tiki Tavi', 'Need for Speed', 'The Run', 'TY7Rxae4pjU', ''),
(250, 'Endless Boogie', 'Empty Eye', 'Need for Speed', 'The Run', '6W2rbEUDi6g', ''),
(251, 'Gary Clark Jr.', 'Don\'t Owe You A Thang', 'Need for Speed', 'The Run', 'OFIWstcaoLc', 'Stage 1 - West Coast'),
(252, 'Girls Against Boys', 'Bullet Proof Cupid', 'Need for Speed', 'The Run', 'SKoM5OphLMA', 'Stage 7 - Chicago Approach'),
(253, 'Handsome Furs', 'Damage', 'Need for Speed', 'The Run', 'sQJbYjj6fN0', ''),
(254, 'London Souls', 'The Sound', 'Need for Speed', 'The Run', 'lwTCRDP0-Qk', ''),
(255, 'Lykke Li', 'Get Some', 'Need for Speed', 'The Run', '-TTPGAy5H_E', 'Stage 9 - State Forest'),
(256, 'Mastodon', 'Curl Of The Burl', 'Need for Speed', 'The Run', 'UJq0YPZFk0A', ''),
(257, 'Middle Class Rut', 'Alive Or Dead', 'Need for Speed', 'The Run', 'KhurFWOmsZk', ''),
(258, 'Ministry', 'N.W.O.', 'Need for Speed', 'The Run', 'x_RRJKfNPpA', 'Stage 3 - Death Valley and Stage 4 - Desert Hills'),
(259, 'Red Fang', 'Prehistoric Dog', 'Need for Speed', 'The Run', 'cmLmpgWiDzM', 'Old Spice; iOS Trailer.'),
(260, 'Reverend Horton Heat', 'Big Red Rocket of Love', 'Need for Speed', 'The Run', 'OzkGzvWT7rY', 'Stage 8 - The Great Lakes'),
(261, 'Rival Sons', 'Save Me', 'Need for Speed', 'The Run', 'ufMkhS29YkI', ''),
(262, 'The Black Angels', 'Better Off Alone', 'Need for Speed', 'The Run', 'e_LuAPr_2Jk', 'Sports Illustrated Teaser Trailer '),
(263, 'UNKLE', 'Money and Run', 'Need for Speed', 'The Run', 'wXdk_XCEoCo', ''),
(264, 'Ritmo Machine', 'La Calle', 'Need for Speed', 'The Run', 'sK2NFVHNToM', 'Stage 10 - East Coast. Chrissy Teigen NFS The Run Demo. Sports Illustrated - Behind the Scenes'),
(265, 'MonstrO', 'Solar', 'Need for Speed', 'The Run', 'MZL1Gug-GjM', ''),
(266, 'T.I. Presents the P$C', 'Do Ya Thang', 'Need for Speed', 'Most Wanted', 's_x_8cSyPCo', ''),
(267, 'Rock', 'I Am Rock', 'Need for Speed', 'Most Wanted', '3__BqswMzVc', 'Izzy (no. 12). Also in Java version; Official Trailer; Cop Damage in NFS Most Wanted. Speedtrap Tutorial.'),
(268, 'Suni Clay', 'In a Hood Near You', 'Need for Speed', 'Most Wanted', 'clBWCRBlYfk', 'Big Lou (no. 11). Appeared in demo version. Drag Tutorial. Toolbooth Tutorial.'),
(269, 'The Perceptionists', 'Let\'s Move', 'Need for Speed', 'Most Wanted', 'txXG_BckcL0', 'JV (no. 4). Appears in PS2 demo.'),
(270, 'Juvenile', 'Sets Go Up', 'Need for Speed', 'Most Wanted', 'sSaPryyAuL4', ''),
(271, 'Hush', 'Fired Up', 'Need for Speed', 'Most Wanted', 'Q67lu2Gurx8', 'Interview With NFS Most Wanted Art Director'),
(272, 'DJ Spooky and Dave Lombardo', 'B-Side Wins Again (feat. Chuck D)', 'Need for Speed', 'Most Wanted', 'yyvjcmQd1xE', 'Appears in PS2 demo. E3 trailer; trailer in Bonus DVD; Rockport city movie showcases'),
(273, 'Lupe Fiasco', 'Tilted', 'Need for Speed', 'Most Wanted', 'l795yjIl814', 'Also in Java version.'),
(274, 'Ils', 'Feed the Addiction', 'Need for Speed', 'Most Wanted', 'khHcKW93CeM', 'Earl (no. 9). Exotics Cars of NFS Most Wanted'),
(275, 'Celldweller', 'One Good Reason', 'Need for Speed', 'Most Wanted', 'j_2XZsYTh6Y', 'Ronnie (no. 3). Instrumental version in game. Pursuits in NFS Most Wanted '),
(276, 'Hyper', 'We Control', 'Need for Speed', 'Most Wanted', 'lF5rySfKLDA', 'Jewels (no. 8). Also in Java version.'),
(277, 'Static-X', 'Skinnyman', 'Need for Speed', 'Most Wanted', '98qG3IDITtc', 'Appeared in demo version. Also in Java version.'),
(278, 'Dieselboy + Kaos', 'Barrier Break', 'Need for Speed', 'Most Wanted', 'L_UdkpCpBuY', 'Baron (no. 10).'),
(279, 'Disturbed', 'Decadence', 'Need for Speed', 'Most Wanted', 'CZ8NAN7wobE', 'Vic (no. 13). Car Customization in NFS Most Wanted'),
(280, 'The Prodigy', 'You\'ll Be Under My Wheels', 'Need for Speed', 'Most Wanted', 'C8v68vXIa6A', 'Bull (no. 2). PSP Trailer.'),
(281, 'Ekstrak', 'Hard Drivers', 'Need for Speed', 'Carbon', 'QjKRyszA1ac', ''),
(282, 'The Roots & BT', 'Tao of the Machine (Scott Humphrey\'s Remix)', 'Need for Speed', 'Most Wanted', '4sMP_7AVpZE', 'Sonny (no. 15)'),
(283, 'Stratus', 'You Must Follow (Evol Intent VIP)', 'Need for Speed', 'Most Wanted', 'FBIq9PiO68Y', 'Kaze (no. 7). Appeared in demo version.'),
(284, 'Mastodon', 'Blood and Thunder', 'Need for Speed', 'Most Wanted', 'L0F_Ktrefts', 'Interview with NFS Most Wanted Senior Producer'),
(285, 'Ekstrak', 'Limited Slip', 'Need for Speed', 'Carbon', 'RPjchd3PXI0', 'PlayStation 3 Trailer - Online '),
(286, 'Pharrell', 'Show You How To Hustle', 'Need for Speed', 'Carbon', 'Q8qHEhXPzWw', ''),
(287, 'Evol Intent & Mayhem & Thinktank', 'Broken Sword', 'Need for Speed', 'Most Wanted', 'BJLNjQEo3cs', 'Ming (no. 6).'),
(288, 'Part 2 & Fallacy', 'One of Dem Days (Remix)', 'Need for Speed', 'Carbon', 'd5lxo7De71M', ''),
(289, 'Bullet for My Valentine', 'Hand of Blood', 'Need for Speed', 'Most Wanted', '0zvIJ2pPMRE', ''),
(290, 'Paul Linford and Chris Vrenna', 'The Mann', 'Need for Speed', 'Most Wanted', '1pQFS2WybW4', ''),
(291, 'Paul Linford and Chris Vrenna', 'Most Wanted Mash Up', 'Need for Speed', 'Most Wanted', 'dItbwjHq5pU', ''),
(292, 'Avenged Sevenfold', 'Blinded In Chains', 'Need for Speed', 'Most Wanted', 'sJxTq8xz43U', 'Taz (no. 14). How to Evade in Pursuits.'),
(293, 'Spank Rock', 'What It Look Like', 'Need for Speed', 'Carbon', 'XoGhRGWp-XA', 'Sal'),
(294, 'Jamiroquai', 'Feels Just Like It Should (Timo Maas Remix)', 'Need for Speed', 'Most Wanted', 'MtohYBDHD-o', ''),
(295, 'Styles of Beyond', 'Nine Thou (Superstars Remix)', 'Need for Speed', 'Most Wanted', 'nkD67MEBkog', 'Webster (no. 5). Appeared in demo version; Trailer (From the Black Edition DVD)'),
(296, 'Tigarah', 'Girl Fight (Mr D Hyphy Remix)', 'Need for Speed', 'Carbon', 'bfBlfC7tYtE', 'Own the City Nintendo DS Trailer. Nintendo Wii Trailer '),
(297, 'Celldweller', 'Shapeshifter (feat. Styles of Beyond)', 'Need for Speed', 'Most Wanted', 'sNlnWkE8hVU', 'Razor (no. 1). Mustang Trailer; Rog and the Black List '),
(298, 'Paul Linford', 'Kick It Up a Notch', 'Need for Speed', 'Most Wanted', 'VbygG7fj_n4', ''),
(299, 'Paul Linford', 'Feels Good Donit', 'Need for Speed', 'Most Wanted', '4upE4EboIIg', ''),
(300, 'Paul Linford', 'My My Missy', 'Need for Speed', 'Most Wanted', 'Zqxy87QqHB8', ''),
(301, 'Sway', 'Hype Boys', 'Need for Speed', 'Carbon', 'acc3b8svrTE', 'Darius (Stacked Deck)'),
(302, 'Paul Linford', 'Don\'t Like It Do Ya', 'Need for Speed', 'Most Wanted', '2Y-FaIeeozk', ''),
(303, 'Paul Linford', 'Ya Think', 'Need for Speed', 'Most Wanted', 'RtL8Uwd-AYc', ''),
(304, 'Paul Linford', 'Not Sure \'bout This T', 'Need for Speed', 'Most Wanted', 'DJgGMNNgOrY', ''),
(305, 'Paul Linford', 'This Doesn\'t Look Good', 'Need for Speed', 'Most Wanted', 'J0dFqSivFVc', ''),
(306, 'Roots Manuva', 'No Love', 'Need for Speed', 'Carbon', 'uf-2mHkELXo', ''),
(307, 'Paul Linford', 'Layin\' Low', 'Need for Speed', 'Most Wanted', '5N2DIyT4xgM', ''),
(308, 'Paul Linford', 'Bet\'r Ride', 'Need for Speed', 'Most Wanted', '9lluXCe--rU', ''),
(309, 'Paul Linford', 'Kiss Yerss Goodbye', 'Need for Speed', 'Most Wanted', 'U8bkf23Jp2s', ''),
(310, 'Paul Linford', 'Take That Dawg', 'Need for Speed', 'Most Wanted', 'EI0YRKvr49Y', ''),
(311, 'Paul Linford', 'Busted', 'Need for Speed', 'Most Wanted', 'Uiae31NpY7Q', 'Hero loses his BMW and gets busted'),
(312, 'Paul Linford', 'Stakes Are Higher', 'Need for Speed', 'Most Wanted', 'lYpJh6uI24o', 'Cutscene where Hero gets on the racers party at the docks'),
(313, 'Paul Linford', 'Lucky Break', 'Need for Speed', 'Most Wanted', 'akyCy16DtHM', 'Prologue cutscene \"Six days ago...\"'),
(314, 'Lady Sovereign', 'Love Me Or Hate Me', 'Need for Speed', 'Carbon', 'HwQfDkhD4V0', ''),
(315, '30 Seconds to Mars', 'Night of the Hunter', '', 'Shift 2 Unleashed', 'zK268TLKCK4', ''),
(316, '30 Seconds to Mars', 'Night of the Hunter (Gladiator Remix)', '', 'Shift 2 Unleashed', 'f1thgdNvzDs', ''),
(317, '30 Seconds to Mars', 'Night of the Hunter (Dirty Remix)', '', 'Shift 2 Unleashed', 'QV91Dn7qeW8', ''),
(318, '30 Seconds to Mars', 'Night of the Hunter (Cinematic Remix)', '', 'Shift 2 Unleashed', 'OfXw3_BK6V0', ''),
(319, 'Grandmaster Flash and the Furious Five', 'Scorpio', 'Need for Speed', 'Carbon', '_IDNAFDalk4', ''),
(320, 'Anberlin', 'We Owe This to Ourselves (Gladiator Remix)', '', 'Shift 2 Unleashed', 'B1bpsWpzWwA', ''),
(321, 'Anberlin', 'We Owe This to Ourselves (Dirty Remix)', '', 'Shift 2 Unleashed', 'FwIgAU0ga58', ''),
(322, 'Dynamite MC', 'Bounce', 'Need for Speed', 'Carbon', 'ReLEYTu2vRM', 'Colin (TFK); appeared in demo version. Also in Java version.'),
(323, 'Anberlin', 'We Owe This to Ourselves (Cinematic Remix)', '', 'Shift 2 Unleashed', 'Lu_uUSv_gFY', ''),
(324, 'Biffy Clyro', 'Mountains', '', 'Shift 2 Unleashed', 'NfzwM4pdyxU', ''),
(325, 'Dynamite MC', 'After Party', 'Need for Speed', 'Carbon', 't0q-l2VKnoM', 'Wolf (TFK)'),
(326, 'Biffy Clyro', 'Mountains (Gladiator Remix)', '', 'Shift 2 Unleashed', 'O0mZldBbO1k', ''),
(327, 'Biffy Clyro', 'Mountains (Dirty Remix)', '', 'Shift 2 Unleashed', 'iZqnjYRJ28I', ''),
(328, 'Biffy Clyro', 'Mountains (Cinematic Remix)', '', 'Shift 2 Unleashed', 'lFFMgHNAagc', ''),
(329, 'The Bravery', 'Ours', '', 'Shift 2 Unleashed', 'h8-gSnZe8as', ''),
(330, 'The Bravery', 'Ours (Gladiator Remix)', '', 'Shift 2 Unleashed', 'YEmEgiReiXc', ''),
(331, 'The Bravery', 'Ours (Dirty Remix)', '', 'Shift 2 Unleashed', 'n_pF9yodzXk', ''),
(332, 'The Bravery', 'Ours (Cinematic Remix)', '', 'Shift 2 Unleashed', 'PYCzMkW9jvo', ''),
(333, 'Ladytron', 'Sugar (Jagz Kooner Remix)', 'Need for Speed', 'Carbon', 'ng1WYWbB2I0', 'Appeared in demo version. Also in Nintendo DS Version'),
(334, 'Ladytron', 'Fighting in Built Up Areas', 'Need for Speed', 'Carbon', 'nQxBRxXKKPU', 'Kenji (Bushido)'),
(335, 'Yonderboi', 'People Always Talk About The Weather (Junkie XL Remix)', 'Need for Speed', 'Carbon', 'QxpD1gBLW58', ''),
(336, 'Gary Numan', 'Are \'Friends\' Electric?', 'Need for Speed', 'Carbon', 'AcEHK6ibaR0', ''),
(337, 'Goldfrapp', 'Ride A White Horse (Serge Santiago Remix)', 'Need for Speed', 'Carbon', 'tLl-hiC3qAE', 'Also in Nintendo DS Version'),
(338, 'Tomas Andersson', 'Washing Up (Tiga Remix)', 'Need for Speed', 'Carbon', 'JViAwrEtZcg', ''),
(339, 'Tiga', 'Good As Gold', 'Need for Speed', 'Carbon', 'yg8aiowysiE', 'Canyon Duel Game Play Trailer. PlayStation 3 Trailer - San Juan '),
(340, 'Vitalic', 'My Friend Dario', 'Need for Speed', 'Carbon', 'hEttqBT5qzs', 'Also in Nintendo DS Version'),
(341, 'Melody', 'Feel The Rush (Junkie XL Remix)', 'Need for Speed', 'Carbon', 'SLdP6_BjFEk', 'Yumi (Bushido) '),
(342, 'Escape the Fate', 'Issues (Gladiator Remix)', '', 'Shift 2 Unleashed', 'pvOFKETtQVQ', ''),
(343, 'Escape the Fate', 'Issues (Dirty Remix)', '', 'Shift 2 Unleashed', 'dtXkyE7-Ck8', ''),
(344, 'Escape the Fate', 'Issues (Cinematic Remix)', '', 'Shift 2 Unleashed', 'Hd-9HcmkY1E', ''),
(345, 'Hollywood Undead', 'Levitate (Gladiator Remix)', '', 'Shift 2 Unleashed', 'h6ko4w-00Kg', 'Autolog Time Attack Challenge '),
(346, 'Hollywood Undead', 'Levitate (Dirty Remix)', '', 'Shift 2 Unleashed', 'HyT6YPEQDqw', ''),
(347, 'Hollywood Undead', 'Levitate (Cinematic Remix)', '', 'Shift 2 Unleashed', 'Gtg9cpKuLWk', ''),
(348, 'The Presets', 'Steamworks', 'Need for Speed', 'Carbon', '6ZgST08tkiM', 'Neville'),
(349, 'Jimmy Eat World', 'Action Needs an Audience (Gladiator Remix)', '', 'Shift 2 Unleashed', 'YPM_nv08_9E', ''),
(350, 'Jimmy Eat World', 'Action Needs an Audience (Dirty Remix)', '', 'Shift 2 Unleashed', '7xg1ctTbB9g', ''),
(351, 'Jimmy Eat World', 'Action Needs an Audience (Cinematic Remix)', '', 'Shift 2 Unleashed', 'BKgENzzm1Gs', ''),
(352, 'Rise Against', 'Help Is On The Way (Gladiator Remix)', '', 'Shift 2 Unleashed', 'Pw23oEjJO8U', 'Launch Trailer '),
(353, 'Rise Against', 'Help Is On The Way (Dirty Remix)', '', 'Shift 2 Unleashed', '85qKYhDU0ug', ''),
(354, 'Rise Against', 'Help Is On The Way (Cinematic Remix)', '', 'Shift 2 Unleashed', '9JdYt56pf9Y', ''),
(355, 'Stone Temple Pilots', 'Take a Load Off (Gladiator Remix)', '', 'Shift 2 Unleashed', '-JJMx4Mcx_U', ''),
(356, 'Stone Temple Pilots', 'Take a Load Off (Dirty Remix)', '', 'Shift 2 Unleashed', 'KNGuD95m6Nw', ''),
(357, 'Stone Temple Pilots', 'Take a Load Off (Cinematic Remix)', '', 'Shift 2 Unleashed', '_9mj-RI4YO4', ''),
(358, 'Eagles of Death Metal', 'Don\'t Speak (I Came to Make a Bang)', 'Need for Speed', 'Carbon', 'YPCJYVdww2w', 'Nikki; appeared in demo version. Also in Nintendo DS Version'),
(359, 'Switchfoot', 'The Sound (Gladiator Remix)', '', 'Shift 2 Unleashed', 'EdbCDkBuh-g', ''),
(360, 'Switchfoot', 'The Sound (Dirty Remix)', '', 'Shift 2 Unleashed', 'h0mtR7Tmeqc', ''),
(361, 'Switchfoot', 'The Sound (Cinematic Remix)', '', 'Shift 2 Unleashed', '0Inolfdap6M', ''),
(362, 'Priestess', 'I Am The Night Colour Me Black', 'Need for Speed', 'Carbon', '-k0ZUcx7t-E', 'Also in Nintendo DS Version'),
(363, 'Anberlin', 'We Owe This to Ourselves', '', 'Shift 2 Unleashed', '4V0AmxPG0sU', ''),
(364, 'Wolfmother', 'Joker and The Thief', 'Need for Speed', 'Carbon', 'hbtjlkpmZ14', 'Samson (21st Street Crew); also in Nintendo DS Version'),
(365, 'Valient Thorr', 'Heatseeker', 'Need for Speed', 'Carbon', 'l0l90F0SrqE', ''),
(366, 'The Vacation', 'I\'m No Good', 'Need for Speed', 'Carbon', 'e5f8heo6f7U', ''),
(367, 'Escape the Fate', 'Issues', '', 'Shift 2 Unleashed', 'W2i237xj2Mk', ''),
(368, 'The Bronx', 'Around The Horn', 'Need for Speed', 'Carbon', 'GJZEO424nZY', ''),
(369, 'Hollywood Undead', 'Levitate', '', 'Shift 2 Unleashed', 'kV36a7yloeo', 'Autolog Drift Challenge; Mobile Trailer; Career Tour Trailer '),
(370, 'Jimmy Eat World', 'Action Needs an Audience', '', 'Shift 2 Unleashed', 'T3NWH0k4L7A', ''),
(371, 'Rise Against', 'Help Is On The Way', '', 'Shift 2 Unleashed', 'JHiqGqoIGII', 'Fly Away Sweepstakes'),
(372, 'Stone Temple Pilots', 'Take a Load Off', '', 'Shift 2 Unleashed', 'L69lQB8zBJw', ''),
(373, 'Switchfoot', 'The Sound (John M. Perkins Blues)', '', 'Shift 2 Unleashed', '8UnR58CdToA', ''),
(374, 'Metro Riots', 'Thee Small Faces', 'Need for Speed', 'Carbon', '4Car7OP_e0g', 'Also in Java version. '),
(375, 'Kyuss', 'Hurricane', 'Need for Speed', 'Carbon', '0eT-HKmC-Gw', 'Angie (21st Street Crew)'),
(376, 'Every Move a Picture', 'Signs of Life', 'Need for Speed', 'Carbon', 'mkk5_QGV3YM', 'Also in Nintendo DS and Java Version. Xbox 360 Trailer - Mazda Speed '),
(377, '30 Seconds to Mars', 'Edge of the Earth', 'Need for Speed', 'Hot Pursuit (2010)', 'PlJBUaozeM8', 'Appears in game opening. Announcement Trailer.'),
(378, 'Airbourne', 'Blackjack', 'Need for Speed', 'ProStreet', 'Ud2fvVtGb8w', 'Appeared in demo version; Also in Nintendo DS Version'),
(379, 'Avenged Sevenfold', 'Almost Easy', 'Need for Speed', 'ProStreet', 'HpGdZKEfVls', 'Also in Nintendo DS Version'),
(380, 'Bad Religion', 'The Resist Stance', 'Need for Speed', 'Hot Pursuit (2010)', '8nygjciFQBk', ''),
(381, 'Bloc Party', 'Prayer (Does It Offend You Yeah Remix)', 'Need for Speed', 'ProStreet', 'y1F6WyEtvTA', ''),
(382, 'Chromeo', 'Fancy Footwork (Guns N\' Bombs Remix)', 'Need for Speed', 'ProStreet', 'SZR48_htrkU', 'Appeared in demo version.'),
(383, 'Clutch', 'Power Player', 'Need for Speed', 'ProStreet', 'gm309v8ybJQ', ''),
(384, 'CSS', 'Odio Odio Odio Sorry C', 'Need for Speed', 'ProStreet', '7smfqoTv_Zc', ''),
(385, 'Datarock', 'I Used To Dance With My Daddy (Karma Harvest Mix)', 'Need for Speed', 'ProStreet', 'mnCA1QqvFFc', ''),
(386, 'Benny Benassi', 'Cinema (feat. Garry Go)', 'Need for Speed', 'Hot Pursuit (2010)', 'Jo8kz-ekR9g', ''),
(387, 'Digitalism', 'Pogo', 'Need for Speed', 'ProStreet', '0WAYKeefp0M', ''),
(388, 'Black Rebel Motorcycle Club', 'Conscience Killer', 'Need for Speed', 'Hot Pursuit (2010)', 'vGSL3-HBsWM', 'Also in iOS Version; On Tour in Chicago; iOS intro.'),
(389, 'Dude \'n Nem', 'Watch My Feet', 'Need for Speed', 'ProStreet', '-8lkKaEUHNI', ''),
(390, 'DUNE', 'A Blast Beat', 'Need for Speed', 'ProStreet', 'aPZF1iULBZ0', 'Also in Nintendo DS Version'),
(391, 'Foreign Islands', 'We Know You Know It', 'Need for Speed', 'ProStreet', 'AzSIju039q0', ''),
(392, 'Chiddy Bang', 'Opposite of Adults', 'Need for Speed', 'Hot Pursuit (2010)', 'eXBfbBnV33I', 'Also in Wii Version (Instrumental); Races (only) (Xbox 360); Gameplay Trailer '),
(393, 'Junkie XL', 'More (Junk O Flamenco Remix) (feat. Lauren Rocket)', 'Need for Speed', 'ProStreet', 'V2czSBDrlTY', ''),
(394, 'Junkie XL', 'More (Junk O Rock Remix) (feat. Lauren Rocket)', 'Need for Speed', 'ProStreet', 'UMFXV990oN8', 'Appeared in demo version.'),
(395, 'Junkie XL', 'More (Junk O Punk Remix) (feat. Lauren Rocket)', 'Need for Speed', 'ProStreet', 'cEwJzwQrx18', ''),
(396, 'Junkie XL', 'More (feat. Lauren Rocket)', 'Need for Speed', 'ProStreet', 'DyECB0wOSNM', 'Also in Nintendo DS Version'),
(397, 'Deadmau5', 'Sofi Needs a Ladder', 'Need for Speed', 'Hot Pursuit (2010)', 'yNy5xcs0W3w', ''),
(398, 'Klaxons', 'Atlantis To Interzone', 'Need for Speed', 'ProStreet', 'yUbkex3qPXU', ''),
(399, 'MSTRKRFT', 'Neon Knights', 'Need for Speed', 'ProStreet', 'y7nqWjhxx2s', ''),
(400, 'Peaches', 'Boys Wanna Be Her (Fire Retouch)', 'Need for Speed', 'ProStreet', 'Wf2ioTofnEQ', 'Appeared in demo version; Also in Nintendo DS Version'),
(401, 'Plan B', 'More Is Enough (feat. Epic Man)', 'Need for Speed', 'ProStreet', '2-F3I7HHdsM', ''),
(402, 'Plan B', 'No Good (Chase & Status and Benni G Remix)', 'Need for Speed', 'ProStreet', 'kesQZ8-try8', 'Appeared in demo version. Also in Nintendo DS Version'),
(403, 'Does It Offend You Yeah?', 'All The Same', 'Need for Speed', 'Hot Pursuit (2010)', 'OFHQlI9POU8', ''),
(404, 'Smallwhitelight', 'Spite', 'Need for Speed', 'ProStreet', 'riQd_88cCTU', ''),
(405, 'The Faint', 'Dropkick The Punks', 'Need for Speed', 'ProStreet', 'DJLi1br9kOE', 'Also in Nintendo DS Version'),
(406, 'The Horrors', 'Draw Japan', 'Need for Speed', 'ProStreet', 'Efy5XLnhNJo', ''),
(407, 'Funeral Party', 'Giant Song', 'Need for Speed', 'Hot Pursuit (2010)', 'c4Etk73FpVk', ''),
(408, 'The Rapture', 'The Sound', 'Need for Speed', 'ProStreet', 'yU-hf1zSlQA', ''),
(409, 'The Toxic Avenger', 'Escape (Bloody Beetroots Remix)', 'Need for Speed', 'ProStreet', 'bHVCG2gKbSg', ''),
(410, 'TV On The Radio', 'Wolf Like Me', 'Need for Speed', 'ProStreet', '5R_6aC6m9Xg', ''),
(411, 'Greenskeepers', 'Live Like You Wanna Live', 'Need for Speed', 'Hot Pursuit (2010)', 'tB4tBtthMFw', ''),
(412, 'UNKLE', 'Restless feat. Josh Homme', 'Need for Speed', 'ProStreet', '75-y6iHiPOw', ''),
(413, 'We Are Wolves', 'Fight and Kiss', 'Need for Speed', 'ProStreet', 'boVJyR-hYZ8', 'Also in Nintendo DS Version'),
(414, 'Wiley', 'Bow E3', 'Need for Speed', 'ProStreet', 'wTGwKONlPWA', ''),
(415, 'Yeah Yeah Yeahs', 'Kiss Kiss', 'Need for Speed', 'ProStreet', '4XmYsgUHIQk', 'Appeared in demo version.'),
(416, 'Year Long Disaster', 'Leda Atomica', 'Need for Speed', 'ProStreet', '27RMVtkTh2s', ''),
(417, 'Yelle', 'A Cause Des Garcons (Riot in Belgium Remix)', 'Need for Speed', 'ProStreet', 'SftpUkiFs6o', ''),
(418, 'Junkie XL', 'Decalomania', 'Need for Speed', 'ProStreet', '6YzA0_7Na4w', 'Original Score Music'),
(419, 'Junkie XL', 'Dampener Rod', 'Need for Speed', 'ProStreet', 'BmS_BBTqTcw', ''),
(420, 'Hadouken!', 'Bombshock', 'Need for Speed', 'Hot Pursuit (2010)', 'XhrBRGYuSTM', 'Also in Wii Version; Wanted Trailer; Autolog Trailer; Launch Trailer '),
(421, 'Junkie XL', 'Choke', 'Need for Speed', 'ProStreet', 'Zmu1l4bR5y8', ''),
(422, 'Junkie XL', 'Idler Lever', 'Need for Speed', 'ProStreet', 'jxlJ43-fH0U', ''),
(423, 'Junkie XL', 'Halogen Blindness', 'Need for Speed', 'ProStreet', 'wlu1mBRmN-E', ''),
(424, 'Junkie XL', 'In the Trunk', 'Need for Speed', 'ProStreet', 'IJk6WqNobm0', ''),
(425, 'Junkie XL', 'Clevis', 'Need for Speed', 'ProStreet', 'owKzcI3EESc', ''),
(426, 'Junkie XL', 'Bezel', 'Need for Speed', 'ProStreet', 'Tfj3gnXc86M', 'Original Score Music'),
(427, 'Killa Kela', 'Get A Rise', 'Need for Speed', 'Hot Pursuit (2010)', 'aQyMjIzR-UU', 'Also in Wii Version'),
(428, 'Junkie XL', '327 - V8', 'Need for Speed', 'ProStreet', 'Ah44lBRgRTo', ''),
(429, 'Junkie XL', 'Castellated Nut', 'Need for Speed', 'ProStreet', 'GN3jjOm0sZU', 'Original Score Music; Nissan GT-R Proto Reveal Trailer'),
(430, 'Klaxons', 'Echoes', 'Need for Speed', 'Hot Pursuit (2010)', 'iyi1iLA5phA', ''),
(431, 'Klaxons', 'Twin Flames', 'Need for Speed', 'Hot Pursuit (2010)', 'ZTkOK20T3Eo', ''),
(432, 'Airbourne', 'Girls in Black', 'Need for Speed', 'Undercover', 'HdfKf7Su5AI', 'Also in Windows Phone version'),
(433, 'Amon Tobin', 'Mighty Micro People', 'Need for Speed', 'Undercover', 'k34TYMiPe94', 'Also in Nintendo DS Version.'),
(434, 'Asian Dub Foundation', 'Burning Fence', 'Need for Speed', 'Undercover', 'zVZNqeYzKc0', 'Instrumental. Also in Nintendo DS Version.'),
(435, 'Bonobo', 'Scuba (Amon Tobin Remix)', 'Need for Speed', 'Undercover', '5E8585juF7w', ''),
(436, 'Lazee', 'Stronger (feat. Dead By April)', 'Need for Speed', 'Hot Pursuit (2010)', 'rk8DiEl554Y', ''),
(437, 'Circlesquare', 'Fight Sounds Part 1', 'Need for Speed', 'Undercover', 'lDxOiBF4dbM', ''),
(438, 'Floor Thirteen', 'Blame It On Me', 'Need for Speed', 'Undercover', 'LSiE681ItBc', 'Let\'s Ride ; Also in Windows Phone version'),
(439, 'Lemonade', 'Big Weekend', 'Need for Speed', 'Hot Pursuit (2010)', 'WgKnnFSJ8t0', 'Also in iOS Version. On Tour - Miami Recap Video'),
(440, 'From First To Last', 'I Once Was Lost But Now Am Profound', 'Need for Speed', 'Undercover', 'Av-mJ8RFuFU', 'Also in Windows Phone version'),
(441, 'Hybrid', 'The Formula of Fear (Matrix Dub)', 'Need for Speed', 'Undercover', '4vsRW0hGL2Y', 'Also in Nintendo DS Version.'),
(442, 'Innerpartysystem', 'This Empty Love', 'Need for Speed', 'Undercover', 'y4GcFBGgUxo', 'Instrumental.'),
(443, 'Justice', 'Genesis', 'Need for Speed', 'Undercover', 'sHL3vmwVCO8', ''),
(445, 'Ladytron', 'Ghosts', 'Need for Speed', 'Undercover', 'w4m-TpUhOHg', 'Nissan 370Z sizzle '),
(446, 'Lupe Fiasco', 'Shining Down', 'Need for Speed', 'Hot Pursuit (2010)', 'u_EvdV8ey9c', 'Also in Wii Version'),
(447, 'Maximum Balloon & Theophilus London', 'Groove Me', 'Need for Speed', 'Hot Pursuit (2010)', '7sudHXXBqIU', 'Also in iOS Version'),
(448, 'Mindless Self Indulgence', 'Never Wanted to Dance (Electro Hertz Mix)', 'Need for Speed', 'Undercover', 'rfybpPZGG3Y', 'The Tri-City Bay Map '),
(449, 'Nine Inch Nails', 'The Mark Has Been Made', 'Need for Speed', 'Undercover', 'XWak7r7E6_4', ''),
(450, 'Nine Inch Nails', 'The Warning (Stefan Goodchild & Doudou N\'Diaye Rose)', 'Need for Speed', 'Undercover', '-CV4M9lY8Ao', ''),
(451, 'Ojos de Brujo', 'Piedras vs. Tanques', 'Need for Speed', 'Undercover', 'EjJoZLb9v2U', ''),
(452, 'M.I.A.', 'Born Free', 'Need for Speed', 'Hot Pursuit (2010)', 'MNoquxEXlpg', 'Also in Wii Version. E3 2010 Trailer.'),
(453, 'Pendulum', '9000 Miles', 'Need for Speed', 'Undercover', 'rgFU6NUI-yE', 'Also in Nintendo DS Version.'),
(454, 'New Politics', 'Yeah Yeah Yeah', 'Need for Speed', 'Hot Pursuit (2010)', '2iTOqJJeeNk', 'Also in Wii Version (Wii Intro Music). Instrumental version used in Roadsters Reborn 101 (first race) intro cutscene'),
(455, 'Pendulum', 'Granite', 'Need for Speed', 'Undercover', 'd24plDUa-q8', 'Also in Nintendo DS Version'),
(456, 'Pendulum', 'Watercolour', 'Need for Speed', 'Hot Pursuit (2010)', 'I3kcVU3gtBQ', 'Also in iOS Version'),
(457, 'Puscifer', 'Indigo Children (JLE Dub Remix)', 'Need for Speed', 'Undercover', 'r8YRg_LK_PU', ''),
(458, 'Puscifer', 'Momma Sed (Tandimonium Mix)', 'Need for Speed', 'Undercover', 'uJ-nxZ0lmDA', ''),
(459, 'Qba Libre and M1', 'God Damn', 'Need for Speed', 'Undercover', 'uja3eE7861k', ''),
(460, 'Recoil', 'Shunt', 'Need for Speed', 'Undercover', '0j3I_ktcFOY', ''),
(461, 'Recoil', 'Vertigen', 'Need for Speed', 'Undercover', 'AxvQz28w8qM', ''),
(462, 'Recoil', 'Want', 'Need for Speed', 'Undercover', 'SZST-Ok7VUo', ''),
(463, 'Splitting Adam', 'On My Own', 'Need for Speed', 'Undercover', 'kddt5eWi4M8', 'Appears in credits.'),
(464, 'Supergrass', 'Bad Blood', 'Need for Speed', 'Undercover', 'iBBGQLzAs4g', ''),
(465, 'Pint Shot Riot', 'Nothing From You (Redanka Remix)', 'Need for Speed', 'Hot Pursuit (2010)', 'JNwJs3VcMg0', 'Also in iOS & Wii Version; Limited Edition Trailer; Android; DLC Armed & Dangerous trailer'),
(466, 'The Fashion', 'Like Knives (Instrumental)', 'Need for Speed', 'Undercover', '6z1GfWXDBFA', ''),
(467, 'The Prodigy', 'First Warning', 'Need for Speed', 'Undercover', 'Zgf4e-K9wnE', 'Driver Job - Theft; Also in Nintendo DS Version'),
(468, 'Plan B', 'Stay Too Long (Pendulum Remix)', 'Need for Speed', 'Hot Pursuit (2010)', '0jLweF06tT8', ''),
(470, 'The Qemists', 'Stompbox (Spor Remix)', 'Need for Speed', 'Undercover', 'TPtv-wUIISc', 'Driver Job - Highway Battle; COPS; Need for Speed Shelby Terlingua with Cheat Code; also in Windows Phone version'),
(471, 'The Whip', 'Fire', 'Need for Speed', 'Undercover', 'hfDJ1s0hSqE', 'LEXUS ISF Reveal '),
(473, 'Teddybears STHLM', 'Devil\'s Music', 'Need for Speed', 'Hot Pursuit (2010)', 'qxOK8T98nc0', ''),
(474, 'Tyga', 'Diamond Life (instrumental)', 'Need for Speed', 'Undercover', 'XGVdLJhkBvg', 'Takedown (trailer)'),
(475, 'Underworld', 'Glam Bucket', 'Need for Speed', 'Undercover', '-F5za8Up43M', ''),
(476, 'Underworld', 'To Heal', 'Need for Speed', 'Undercover', 'nrR6oSnSvzc', ''),
(477, 'Paul Haslinger', 'A Manner Of Speed', 'Need for Speed', 'Undercover', 'Fo5sGuOdFRA', ''),
(478, 'Travie McCoy', 'Superbad (11:34)', 'Need for Speed', 'Hot Pursuit (2010)', 'nllcAEOo8MA', 'Also in Wii Version'),
(479, 'Paul Haslinger', 'The Miami Drift', 'Need for Speed', 'Undercover', 'M59gXZ4J008', ''),
(480, 'Paul Haslinger', 'By Any Means', 'Need for Speed', 'Undercover', '7CeJirCF-KI', ''),
(481, 'Paul Haslinger', 'Man & Machine', 'Need for Speed', 'Undercover', '_Izn4E7mAQ0', ''),
(482, 'Paul Haslinger', 'Slow Burn', 'Need for Speed', 'Undercover', '9XBZ8f47gYs', ''),
(483, 'Paul Haslinger', 'Treacherous Terrain', 'Need for Speed', 'Undercover', 'QRcW4ZiTfu8', ''),
(484, 'Paul Haslinger', 'Powers Up!', 'Need for Speed', 'Undercover', 'tK7gOsv4ato', ''),
(485, 'We Have Band', 'Divisive (Tom Staar Remix)', 'Need for Speed', 'Hot Pursuit (2010)', 'uxF4tyGZy3A', 'Also in iOS and Wii Version; Roadsters Reborn 101 '),
(486, 'Paul Haslinger', 'Zero Sum', 'Need for Speed', 'Undercover', '8VbXKrt_rUg', ''),
(487, 'Paul Haslinger', 'The Setup', 'Need for Speed', 'Undercover', 'SLle85X-s0A', ''),
(488, 'Paul Haslinger', 'Torsion Field', 'Need for Speed', 'Undercover', 'uHr6lGS0kYQ', ''),
(489, 'Paul Haslinger', 'Motion Blur', 'Need for Speed', 'Undercover', '5LjeiRONOtA', ''),
(490, 'Paul Haslinger', 'Friction', 'Need for Speed', 'Undercover', 'AjAL98RjE_k', ''),
(491, 'White Lies', 'Bigger Than Us', 'Need for Speed', 'Hot Pursuit (2010)', 'JW0yynlDmqQ', 'Also in iOS Version'),
(492, 'Paul Haslinger', 'Endemic Speed', 'Need for Speed', 'Undercover', '3RrMOfMf8Hk', ''),
(493, 'Weezer', 'Ruling Me', 'Need for Speed', 'Hot Pursuit (2010)', 'DKzyAkB4aq0', ''),
(494, 'Paul Haslinger', 'In the Blink of an Eye', 'Need for Speed', 'Undercover', 'qY6GjIV_HC4', ''),
(495, 'Paul Haslinger', 'No Line of Sight', 'Need for Speed', 'Undercover', 'wXyEeCKio4s', ''),
(496, 'Paul Haslinger', 'Buying Time', 'Need for Speed', 'Undercover', 'm27sxKXuuHU', ''),
(497, 'Paul Haslinger', 'A Winner\'s Game', 'Need for Speed', 'Undercover', 'APgkuRtyzmg', ''),
(498, 'Paul Haslinger', 'Black Sun Memories', 'Need for Speed', 'Undercover', 'Mf_T5bTPwPA', ''),
(499, 'Marios Takoushis and Vanesa Lorena', 'Hot Pursuit 2010 Score 01', 'Need for Speed', 'Hot Pursuit (2010)', 'dSEPCbEoyt4', ''),
(500, 'Buraka Som Sistema', 'Kalemba (Wegue-Wegue)', 'Need for Speed', 'Shift', 'OpYR7ilLbfo', ''),
(501, 'Marios Takoushis and Vanesa Lorena', 'Hot Pursuit 2010 Score 02', 'Need for Speed', 'Hot Pursuit (2010)', '5JeG8Ld07l4', ''),
(502, 'Deadmau5', 'Ghosts N Stuff', 'Need for Speed', 'Shift', 'yy11WHWYnyo', 'Ray Krieger\'s theme (PSP)'),
(503, 'Marios Takoushis and Vanesa Lorena', 'Hot Pursuit 2010 Score 03', 'Need for Speed', 'Hot Pursuit (2010)', 'FH_uHQYgvkw', ''),
(504, 'Eagles of Death Metal', 'Anything \'Cept The Truth', 'Need for Speed', 'Shift', 'yNliaZCqBLk', 'Wade Johnson\'s theme (PSP)'),
(505, 'Marios Takoushis and Vanesa Lorena', 'Hot Pursuit 2010 Score 04', 'Need for Speed', 'Hot Pursuit (2010)', 'RyAOasNkC1k', ''),
(506, 'Fort Knox 5', 'Insight (The Nextmen Remix)', 'Need for Speed', 'Shift', 'XNPfEqoXgOk', 'Rod Cruz\'s theme (PSP)'),
(507, 'Gallows', 'I Dread The Night', 'Need for Speed', 'Shift', 'eKr0zczQoXU', 'Nate Denver\'s theme (PSP)'),
(508, 'In Case of Fire', 'This Time We Stand', 'Need for Speed', 'Shift', 'iGU7MJB7_2s', ''),
(509, 'Marios Takoushis and Vanesa Lorena', 'Hot Pursuit 2010 Score 05', 'Need for Speed', 'Hot Pursuit (2010)', 'PKFCYsECkLk', ''),
(510, 'Jamal', 'Pull Up', 'Need for Speed', 'Shift', 'qvHxOrqilE0', ''),
(511, 'Kanye West', 'Paranoid (Part 2)', 'Need for Speed', 'Shift', 'Jqr15etQS1Q', ''),
(512, 'Marios Takoushis and Vanesa Lorena', 'Hot Pursuit 2010 Score 06', 'Need for Speed', 'Hot Pursuit (2010)', 'XoNKGKuYdkI', ''),
(513, 'Kasabian', 'Underdog', 'Need for Speed', 'Shift', 'v4g-LwdtL30', 'Marc Demarcher\'s theme (PSP)'),
(514, 'The King Blues', 'The Streets Are Ours', 'Need for Speed', 'Shift', 'o8rTN4kgW0o', ''),
(515, 'Mala Rodriguez', 'Te Convierto', 'Need for Speed', 'Shift', 'NQ2_rGzptBw', ''),
(516, 'Mando Diao', 'Mean Street', 'Need for Speed', 'Shift', 'ySBlokqHbEo', ''),
(517, 'MSTRKRFT', 'Click Click (feat. E-40)', 'Need for Speed', 'Shift', 'c0he8osCM68', ''),
(518, 'N.A.S.A.', 'Whachadoin? (feat. Spank Rock & MIA & Santigold)', 'Need for Speed', 'Shift', 'fyErgJM66p0', 'Aya Vasquez\'s theme (PSP)'),
(519, 'The Prodigy', 'Run With The Wolves', 'Need for Speed', 'Shift', 'Uql3mAPuxdg', ''),
(520, 'The Qemists', 'Lost Weekend (feat. Mike Patton)', 'Need for Speed', 'Shift', 'YT81paWNuv0', 'Also in Java version.'),
(521, 'Regular John', 'Transmitter', 'Need for Speed', 'Shift', 'xSLgvn3I2gM', ''),
(522, 'Rootbeer', 'Under Control', 'Need for Speed', 'Shift', 'ky4fDAN2UQ8', 'Also in Java version. Diablo Montana\'s theme (PSP)'),
(523, 'Shinichi Osawa', 'Electro 411 (Lies In Disguise Mix)', 'Need for Speed', 'Shift', 'U-65g3xrPH0', 'Ryo Wanatabe\'s theme (PSP)'),
(524, 'Spoon Harris & Obernik', 'Baditude', 'Need for Speed', 'Shift', 'K1D23Kl_y84', 'Karol Monroe\'s theme (PSP)'),
(525, 'TOKIO', 'Dogonim', 'Need for Speed', 'Shift', '3FmrTn8alKA', ''),
(526, 'Twisted Wheel', 'Oh What Have You Done', 'Need for Speed', 'Shift', 'si_xptgoncU', ''),
(527, 'Two Fingers', 'High Life (feat. Sway)', 'Need for Speed', 'Shift', '_XNYZ2PuwAI', 'Also in Java version. Alex Fry\'s theme (PSP)'),
(528, 'Trevor Morris', 'Canyon Race 1: Drift Itsumo', 'Need for Speed', 'Carbon', '6ofR2nMsZ-k', ''),
(529, 'Trevor Morris', 'Crew Race 1: Urban Assault', 'Need for Speed', 'Carbon', 'sxOd7P1fQjc', ''),
(530, 'Trevor Morris', 'Canyon Race 2: Control Onegaishmasu', 'Need for Speed', 'Carbon', 'hOFyRJkit-Q', ''),
(531, 'Trevor Morris', 'Don\'t Get Caught', 'Need for Speed', 'Carbon', 'n4nvVDrcJHQ', ''),
(532, 'Alex Metric', 'What Now', 'Need for Speed', 'Nitro', 'OFxufV5Abmg', 'Also in Nintendo DSi Version'),
(533, 'Bloody Beetroots', 'Awesome (feat. Cool Kids)', 'Need for Speed', 'Nitro', 'Mxi75ayesTo', 'Rio De Janeiro '),
(534, 'Crookers', 'Business Man feat. Wiley and Thomas Jules', 'Need for Speed', 'Nitro', 'p3daEah_7ik', ''),
(535, 'Trevor Morris', 'Crew Race 2: Bending Light', 'Need for Speed', 'Carbon', 'kQ7C-6EZOyE', ''),
(536, 'The Crystal Method', 'Sine Language (feat. LMFAO)', 'Need for Speed', 'Nitro', 'To2CRjp2bSc', 'Madrid '),
(537, 'Danko Jones', 'Code of The Road', 'Need for Speed', 'Nitro', 'YXirtB8V2g8', 'Intro.'),
(538, 'Dizzee Rascal', 'Bonkers', 'Need for Speed', 'Nitro', 'UCkhqNQY5KI', 'Also in Nintendo DSi Version'),
(539, 'Drumagick', 'Make It Rock', 'Need for Speed', 'Nitro', 'reR3nQ33qMk', 'Dubai '),
(540, 'Trevor Morris', 'Canyon Race 3: Suckers OgenkiDesuka?', 'Need for Speed', 'Carbon', 'U_jKVDjVPRo', ''),
(541, 'Earl Greyhound', 'Oye Vaya', 'Need for Speed', 'Nitro', 'hbYhiFahRRc', 'Also in Nintendo DSi Version; Madrid '),
(542, 'edIT', 'Freaxxx (feat. Wale and Tre’)', 'Need for Speed', 'Nitro', 'nSRYCprxTkg', ''),
(543, 'Evil 9', 'All The Cash (Alex Metric Remix)', 'Need for Speed', 'Nitro', 'awKazl7_trg', 'Career Mode Video '),
(544, 'Trevor Morris', 'Crew Race 3: Sounding Streets', 'Need for Speed', 'Carbon', 'KVofDWgjesI', ''),
(545, 'Hollywood Holt', 'Can\'t Stop', 'Need for Speed', 'Nitro', 'g5O11-ObWD4', ''),
(546, 'k-os', 'FUN!', 'Need for Speed', 'Nitro', 'HONKy8BbYAE', 'Gamescom Trailer'),
(547, 'Lady Sovereign', 'I Got You Dancing', 'Need for Speed', 'Nitro', 'eEaiUFJQCLM', ''),
(548, 'Major Lazer', 'Hold The Line (feat. Mr. Lex & Santigold)', 'Need for Speed', 'Nitro', 'j4SNtFQZF0A', ''),
(549, 'Trevor Morris', 'Canyon Race 4: Konbawa', 'Need for Speed', 'Carbon', 'FRK9Rq8xbW4', ''),
(550, 'Matt & Kim', 'Daylight (Troublemaker Remix)', 'Need for Speed', 'Nitro', 'krUCX17whXQ', ''),
(551, 'Mickey Factz', 'Yeah Yeah', 'Need for Speed', 'Nitro', 'g1NA9LvB5fI', ''),
(552, 'Pint Shot Riot', 'Not Thinking Straight', 'Need for Speed', 'Nitro', 'MFWHUX7U08o', ''),
(553, 'Placebo', 'Breathe Underwater', 'Need for Speed', 'Nitro', '1qRw52Mop8g', ''),
(554, 'Rise Against', 'Kotov Syndrome', 'Need for Speed', 'Nitro', 'cu1eRB5WmeA', ''),
(555, 'Roots Manuva', 'Buff Nuff', 'Need for Speed', 'Nitro', 'E98G3HYkdiw', ''),
(556, 'Rye Rye', 'Hardcore Girls', 'Need for Speed', 'Nitro', 'udRWDSU_iVM', ''),
(557, 'Street Sweeper Social Club', 'Fight! Smash! Win!', 'Need for Speed', 'Nitro', 'Gw_hAsFtcHo', ''),
(558, 'Taking Back Sunday', 'Lonely Lonely', 'Need for Speed', 'Nitro', '4HeoR-Q1s_4', ''),
(559, 'The Enemy', 'No Time For Tears', 'Need for Speed', 'Nitro', 'ZZXI2kiyYe4', ''),
(560, 'The Gay Blades', 'O Shot (Dmerit Remix)', 'Need for Speed', 'Nitro', '6f3ZPPpVg6I', ''),
(561, 'Two Fingers', 'Jewels And Gems (feat. Sway)', 'Need for Speed', 'Nitro', 'tghTY5vC0RA', 'Cairo '),
(562, 'The Wolfmen', 'Better Days', 'Need for Speed', 'The Run', 'PRy116sfnzo', ''),
(563, 'USS', 'Anti-Venom', 'Need for Speed', 'The Run', 'NwUNlJIaZgA', ''),
(564, 'The Unknown', 'Ready Aim Fire', 'Need for Speed', 'The Run', 'gSnR26HIlwg', ''),
(565, 'Trial Kennedy', 'Best of Tomorrow', 'Need for Speed', 'The Run', 'c2HqM-ltmFg', ''),
(566, 'Tony Cartier', 'Man on a Mission', 'Need for Speed', 'The Run', '_dx6bozpnX8', ''),
(567, 'Tim Myers', 'Life\'s a Party', 'Need for Speed', 'The Run', 'kuQwR9-DlnY', ''),
(568, 'The Vandelles', 'Bomb The Surf', 'Need for Speed', 'The Run', 'LzBCMI_qWHY', ''),
(569, 'The Postelles', 'Sound The Alarms', 'Need for Speed', 'The Run', 'IuCI6jIVYvM', ''),
(570, 'Rom di Prisco', 'Bring That Beat Back (Queensyze Remix)', 'Need for Speed', 'The Run', 'zmUEcfvsABY', ''),
(571, 'Queensyze', 'Aaeyaa', 'Need for Speed', 'The Run', 'U1Qy5WqNDlY', ''),
(572, 'Nu:Tone', 'Shine In', 'Need for Speed', 'The Run', '6LduG9HbUpA', ''),
(573, 'Rom Di Prisco', 'Aquila 303 (Mick Gordon Remix)', 'Need for Speed', 'The Run', 'cTuIw4x5JBg', ''),
(574, 'Rom Di Prisco', 'Cetus 808 (Mick Gordon Remix)', 'Need for Speed', 'The Run', 'GApQjX0scWg', ''),
(575, 'The Lovemakers', 'All Together', 'Need for Speed', 'The Run', 'aZdXt37OCkk', ''),
(576, 'Danny Byrd', 'Tonight', 'Need for Speed', 'The Run', 'XQwbhafmjNY', ''),
(577, 'Branden Daniel', 'Mor Yay', 'Need for Speed', 'The Run', 'pOBHkAwnqAY', ''),
(578, 'Big Omeezy', 'The Nightlife', 'Need for Speed', 'The Run', 'WWIkkvR2NI4', ''),
(579, 'Jeff Dyck & Saki Kaskas', 'Nashat (Remix)', 'Need for Speed', 'The Run', 's4eqlt_bY6E', ''),
(580, 'Saki Kaskas', 'Amourphous (3volution Remix)', 'Need for Speed', 'The Run', 'sK9nTOAXYxk', ''),
(581, 'Mick Gordon', 'Drone (Menu Track)', 'Need for Speed', 'The Run', 'IBbbzIx8OzM', 'Credits'),
(582, 'Brian Tyler', 'Orchestral Chase 1', 'Need for Speed', 'The Run', 'PD3LYGoTJuQ', ''),
(583, 'Brian Tyler', 'Orchestral Chase 2', 'Need for Speed', 'The Run', 'YUC9pf5w4H8', ''),
(584, 'Brian Tyler', 'Orchestral Chase 3', 'Need for Speed', 'The Run', 'poTalUddzF4', ''),
(585, 'Brian Tyler', 'Orchestral Chase 4', 'Need for Speed', 'The Run', '-HrU5fg0l2M', ''),
(586, 'Steve Hillage', 'Four Ever Rainbow (Part 1)', 'Need for Speed', 'Most Wanted (2012)', 'idrAZhJMG2Y', ''),
(587, 'Steve Hillage', 'Four Ever Rainbow (Part 2)', 'Need for Speed', 'Most Wanted (2012)', 'dyySzNqfgeg', ''),
(588, 'Steve Hillage', 'Four Ever Rainbow (Part 3)', 'Need for Speed', 'Most Wanted (2012)', 'vzF7s9eYpbs', ''),
(589, 'Steve Hillage', 'Four Ever Rainbow (Part 4)', 'Need for Speed', 'Most Wanted (2012)', 'r3qMqDRedCo', ''),
(590, 'Mick Gordon', 'Static', 'Need for Speed', 'World', 'ykl2xLTMVro', 'Played when player is idle.'),
(591, 'Mick Gordon', 'That\'s How We Go', 'Need for Speed', 'World', 'aw3qAhyuMNE', ''),
(592, 'Mick Gordon', 'Kustomize', 'Need for Speed', 'World', 'zj-_uvisBiQ', ''),
(593, 'Mick Gordon', 'The World Online', 'Need for Speed', 'World', 'wMD8t-e_Lyg', 'Unused song'),
(594, 'Mick Gordon', 'The Streets', 'Need for Speed', 'World', '2UvtSHDJQC0', ''),
(595, 'Mick Gordon', 'Street Racin\'', 'Need for Speed', 'World', 'GCwvL2NLbWw', ''),
(596, 'Mick Gordon', 'Sexi', 'Need for Speed', 'World', 'DTIWIsw1af0', ''),
(597, 'Gigante Music Boutique', 'Headbanger', 'Need for Speed', 'World', '1HzCmBSXBDQ', ''),
(598, 'Gigante Music Boutique', 'Extreme', 'Need for Speed', 'World', '7DAd1kiDhTE', ''),
(599, 'Donots', 'We Got The Noise', 'Need for Speed', 'Underground 2', 'Rq-S87euROA', ''),
(600, 'No Warning', 'Breeding Insanity', 'Need for Speed', 'Underground 2', 'T_qgp__qMBI', ''),
(601, 'DJ Tiesto', 'Breda 8pm (DJ Montana Edit)', 'Need for Speed', 'Underground 2', 'ErimeAUyCPw', ''),
(602, 'My Chemical Romance', 'Thank You For The Venom', 'Need for Speed', 'Underground 2', '00Z-Gbyb7l8', 'Need For Speed Underground Rivals Trailer'),
(603, 'Hot Water Music', 'The End of The Line', 'Need for Speed', 'Underground 2', 'TuQbUcFnO64', ''),
(608, 'Sin', 'Painful (Morphium Mix)', '', 'V-Rally 2', 'Q_et4IA62Ig', 'Intro'),
(609, 'Piggie Pie', 'Rockin Engine', '', 'V-Rally', 'P2NWSM4_RGE', ''),
(610, 'Piggie Pie', 'African Vibes', '', 'V-Rally', 'Ca5FzF7Q-Xo', ''),
(611, 'Piggie Pie', 'Seventies Drive', '', 'V-Rally', 'SHn2Cwdhb4A', ''),
(612, 'Piggie Pie', 'RPM Doors', '', 'V-Rally', 'UKDEAXEpEkA', ''),
(613, 'Piggie Pie', 'Road Slap', '', 'V-Rally', 'qM16bDu6VxY', ''),
(614, 'Piggie Pie', 'His Name is Mud', '', 'V-Rally', 'gt_4_q-Jdk0', ''),
(615, 'Piggie Pie', 'Heavy Beat', '', 'V-Rally', '73EislZq4VA', ''),
(616, 'Piggie Pie', 'The Krash', '', 'V-Rally', '9cqQ9TnTaLs', ''),
(622, 'A', 'Nothing', '', 'V-Rally 3', 'PrjmdTlo-XQ', ''),
(623, 'Piggy Pie', 'Bacteria', '', 'V-Rally 3', 'c6YqNH9DQHk', 'Main Menu Theme'),
(625, 'Piggy Pie', '30years', '', 'V-Rally 3', 'ikExkWIoAho', 'Time Attack Music (PS2 Version)'),
(626, 'Trevor Morris', 'Meeting Darius', 'Need for Speed', 'Carbon', 'qMPDK3yL9s4', ''),
(627, 'Trevor Morris', 'Stylin\'', 'Need for Speed', 'Carbon', 'N13OrAPDsec', ''),
(628, 'Trevor Morris', 'Ghosts of the Past', 'Need for Speed', 'Carbon', 'JZvdQzEzd1c', ''),
(629, 'Trevor Morris', 'Darius\'s Ultimatum', 'Need for Speed', 'Carbon', 'HdQsGKeuhRM', ''),
(630, 'Trevor Morris', 'You Knew The Rules', 'Need for Speed', 'Carbon', 'tigy2DdD_GQ', ''),
(631, 'Trevor Morris', 'The Five-O', 'Need for Speed', 'Carbon', '2TAXvnqKEuQ', ''),
(632, 'Trevor Morris', 'Recovery', 'Need for Speed', 'Carbon', 'UXt3ksPA4r8', ''),
(633, 'Trevor Morris', 'Out of Site', 'Need for Speed', 'Carbon', 'ch12wvSAHnM', ''),
(634, 'Trevor Morris', 'Finish Line', 'Need for Speed', 'Carbon', 'Q57Ppjp075Y', ''),
(635, 'Legowelt', 'Disco Rout', 'Need for Speed', 'Carbon', 'MLsqs9mLyTQ', 'Deleted in final release. PlayStation 3 Trailer - Cross. PlayStation 3 Trailer - Emmanuelle. Downtown Palmont (Bonus DVD).'),
(636, 'Ekstrak', 'Staggered', 'Need for Speed', 'Carbon', 'nkaOZP5o__A', ''),
(637, 'Ekstrak', 'Induction Kit', 'Need for Speed', 'Carbon', 'dtiBksK4ILA', ''),
(638, 'Ekstrak', 'Belt', 'Need for Speed', 'Carbon', '-TJIyW0AHnE', ''),
(639, 'Ekstrak', 'Diesel Shift', 'Need for Speed', 'Carbon', 'fgd1nU27Ljg', ''),
(640, 'Ekstrak', 'Hard Drivers VIP', 'Need for Speed', 'Carbon', 'LixKNuYbuSw', 'Full Intro '),
(641, 'Ekstrak', 'Muscle Theme', 'Need for Speed', 'Carbon', 'Jd_3A9jMWAk', ''),
(642, 'Tinie Tempah', 'Frisky (Instrumental Mix)', 'Need for Speed', 'Hot Pursuit (2010)', 'fSO_H42ujmU', 'Also in PS3 Beta Build Text Files'),
(643, 'Hadouken!', 'Turn The Lights Out', 'Need for Speed', 'Hot Pursuit (2010)', 'PRhuaTFNBUQ', 'Supposed to appear in other versions.'),
(644, 'The Futureheads', 'The Connector', 'Need for Speed', 'Hot Pursuit (2010)', '0nhnZtBVcnY', 'Also in PS3 Beta Build Text Files'),
(645, '!!! (Chk Chk Chk)', 'The Hammer', 'Need for Speed', 'Hot Pursuit (2010)', 'ds3niarvU_8', 'Sun Sand and Supercars Trailer. Demo - Roadsters Reborn 101. Also in PS3 Beta Build Text Files. On Tour Owns San Francisco'),
(646, 'Junkie XL', 'Brake Pipe and Hose', 'Need for Speed', 'ProStreet', 'eVwoSViYSvA', 'Intro. PlayStation 3 Trailer - Drift '),
(647, 'Neon Plastix', 'On Fire', 'Need for Speed', 'ProStreet', 'i1B6Z4let5w', ''),
(648, 'Splitting Adam', 'Vertical Drop', 'Need for Speed', 'ProStreet', '_x8JMhMXurI', 'Found in game files.'),
(649, 'Black Rebel Motorcycle Club', 'Mama Taught Me Better', 'Need for Speed', 'The Run', 'PBCreUcT7-Q', ''),
(650, 'The Night Marchers', 'Tropical Depression', 'Need for Speed', 'The Run', 'CAVS378C8Y4', ''),
(654, 'Brian Tyler', 'Need For Speed The Run', 'Need for Speed', 'The Run', 'prU2oRkCLDk', 'Death From Above race. Race against Marcus Blackwell'),
(655, 'Brian Tyler', 'Apex', 'Need for Speed', 'The Run', 'qUoPFFnTGKE', ''),
(656, 'Brian Tyler', 'Rapid Formation', 'Need for Speed', 'The Run', 'gLWURQ7gRoI', ''),
(657, 'Brian Tyler', 'Front End', 'Need for Speed', 'The Run', 'XNoshU1EgZE', 'First time you open the Main Menu'),
(658, 'Brian Tyler', 'The Limit', 'Need for Speed', 'The Run', 'tG4AvM3Kqt4', ''),
(659, 'Brian Tyler', 'Insane Face', 'Need for Speed', 'The Run', 'a2X2sP8OXPw', ''),
(660, 'Brian Tyler', 'Sicker Than You', 'Need for Speed', 'The Run', 'OOOBqksJPxE', 'Summit Independence Pass race'),
(661, 'Brian Tyler', 'Crusher', 'Need for Speed', 'The Run', '58HJuSlGo24', 'Car Crusher Cutscene'),
(662, 'Brian Tyler', 'Overunder', 'Need for Speed', 'The Run', 'q1i7Bs9wl7Y', ''),
(663, 'Brian Tyler', 'Front End American', 'Need for Speed', 'The Run', 'TYJqP2E0C7E', 'Main Menu'),
(664, 'Brian Tyler', 'Palms of Sweat', 'Need for Speed', 'The Run', '184alYAVkj0', ''),
(665, 'Brian Tyler', 'Knife Edge', 'Need for Speed', 'The Run', 'ZoSsB1TAGLo', 'Police Chase part of Nob Hill'),
(666, 'Brian Tyler', 'Into The Warehouse', 'Need for Speed', 'The Run', 'whw1lI3AZig', 'First \"Select Car\" scene.'),
(667, 'Brian Tyler', 'That Is Impossible', 'Need for Speed', 'The Run', 'QJyfBg8A3Ig', ''),
(668, 'Brian Tyler', 'Rival', 'Need for Speed', 'The Run', '7lNU0KhGTnU', ''),
(669, 'Brian Tyler', 'Fail', 'Need for Speed', 'The Run', 'QJzbOo87bwU', 'Used for the Game Over Screen'),
(670, 'Brian Tyler', 'Scrappy Rubber', 'Need for Speed', 'The Run', 'mWM3ATJ6MJw', ''),
(671, 'Brian Tyler', 'Gas Station Dust', 'Need for Speed', 'The Run', '3mj125D10MY', 'Gas Station Cutscene before the Nikki and Mila race'),
(672, 'Brian Tyler', 'Choker', 'Need for Speed', 'The Run', 'zxf_YnON1UM', 'Summit Independence Pass race'),
(673, 'Brian Tyler', 'Win', 'Need for Speed', 'The Run', 'VtSiI4sck_g', ''),
(674, 'Brian Tyler', 'Crossover', 'Need for Speed', 'The Run', 'WknFROaE88M', ''),
(675, 'Brian Tyler', 'Think Thrice', 'Need for Speed', 'The Run', 'ocd91jdBxSY', ''),
(676, 'Brian Tyler', 'Tear Down', 'Need for Speed', 'The Run', 'BPGdruDwYF4', ''),
(677, 'Brian Tyler', 'Blurred', 'Need for Speed', 'The Run', 'caT6y4QbXmI', ''),
(678, 'Brian Tyler', 'The Meet', 'Need for Speed', 'The Run', 'CyfdixEMSBw', ''),
(679, 'Brian Tyler', 'The Journey Continues', 'Need for Speed', 'The Run', 'eeTSsbHhuvY', ''),
(680, 'Girlschool', 'C\'mon Lets Go', 'Need for Speed', 'The Run', 'BYNWo93fPG8', 'Stage 3 - Death Valley'),
(681, 'Jim Latham', 'Original Music Score (10 songs)', 'Need for Speed', 'Underground', 'MLFWAwEz4oY', ''),
(683, 'Chase and Status', 'Pieces', 'Need for Speed', 'Shift', 'URElPj2_Pj0', ''),
(685, 'Alistair Hirst', 'Ferrari 512TR', 'Road & Track Presents:', 'The Need for Speed', 'Frm-TdZyN2g', ''),
(686, 'Alistair Hirst', 'Porsche 911 Carrera', 'Road & Track Presents:', 'The Need for Speed', '54L6YrrILrk', ''),
(687, 'Alistair Hirst', 'Lamborghini Diablo VT', 'Road & Track Presents:', 'The Need for Speed', 'O14Wgu1bHSI', ''),
(688, 'Alistair Hirst', 'Acura NSX', 'Road & Track Presents:', 'The Need for Speed', '1MLLyJlqcQY', ''),
(689, 'Alistair Hirst', 'Mazda RX-7', 'Road & Track Presents:', 'The Need for Speed', '3U8cLi-Yu6k', ''),
(690, 'Alistair Hirst', 'Toyota Supra Turbo', 'Road & Track Presents:', 'The Need for Speed', 'ypfJ2Uy3ZlM', ''),
(691, 'Alistair Hirst', 'Chevrolet Corvette ZR-1', 'Road & Track Presents:', 'The Need for Speed', 'u7RR8edK2Ss', ''),
(692, 'Alistair Hirst', 'Dodge Viper RT/10', 'Road & Track Presents:', 'The Need for Speed', '-tyfMky4-zA', ''),
(694, 'Haezer', 'Troublemaker (feat. Tumi)', 'Need for Speed', 'Rivals', 'LnXsIA14sW0', 'Ferrari DLC Pack; Personalization Features Gameplay Trailer; Unlocking: BMW M3 GTS & Ferrari F12berlinetta'),
(696, 'Stephen Root & Steve Emney', 'Menu', '', 'Burnout 1', 'J5DKFq9BiPg', ''),
(697, 'Stephen Root & Steve Emney', 'Nought 260', '', 'Burnout 1', 'b8rF5fumRXI', ''),
(698, 'Stephen Root & Steve Emney', 'Oversteer', '', 'Burnout 1', 'kGgm6u7BRh4', ''),
(699, 'Stephen Root & Steve Emney', 'Eurorush', '', 'Burnout 1', 'kwBx689GB2E', ''),
(700, 'Stephen Root & Steve Emney', 'Heart Failure', '', 'Burnout 1', 'zm0BhCLA1GU', ''),
(701, 'Stephen Root & Steve Emney', 'In Control', '', 'Burnout 1', 'Vz6JwwD1B2M', ''),
(702, 'Stephen Root & Steve Emney', 'Dead Ahead', '', 'Burnout 1', 'DTACS_Kmr3E', ''),
(703, 'Stephen Root & Steve Emney', '66 Kicks', '', 'Burnout 1', 'kJQcYIYn8Pc', ''),
(704, 'Stephen Root & Steve Emney', 'Whiplash', '', 'Burnout 1', 'CP5cMP4A090', ''),
(705, 'Stephen Root & Steve Emney', 'Downtown Drift', '', 'Burnout 1', 'gwrhSD34_2A', ''),
(706, 'Stephen Root & Steve Emney', 'Fatal Instinct', '', 'Burnout 1', 'wokchDhQ1xU', ''),
(707, 'Stephen Root & Steve Emney', 'Credits', '', 'Burnout 1', 'Md2l7DRmU1U', ''),
(708, 'Stephen Root & Steve Emney', 'Bulldozer Blues', 'Burnout', '2: Point of Impact', '4vxtOcjLvJI', ''),
(709, 'Stephen Root & Steve Emney', 'Backlash', 'Burnout', '2: Point of Impact', 'LDPX-7IhVW4', ''),
(710, 'Stephen Root & Steve Emney', 'A Photograph', 'Burnout', '2: Point of Impact', 'tLI1iVZdWJI', ''),
(711, 'Stephen Root & Steve Emney', 'Bridge The Gap', 'Burnout', '2: Point of Impact', 'MKEwhRVPY44', ''),
(712, 'Stephen Root & Steve Emney', 'Panic Attack', 'Burnout', '2: Point of Impact', 'EsTTAjaNThM', ''),
(713, 'Stephen Root & Steve Emney', 'Pass Me By', 'Burnout', '2: Point of Impact', '5woHE_cEjSo', ''),
(714, 'Stephen Root & Steve Emney', 'Destroyer Mix', 'Burnout', '2: Point of Impact', 'k6g5so6TIqQ', ''),
(715, 'Stephen Root & Steve Emney', 'The Miracle Mile', 'Burnout', '2: Point of Impact', 'sqNNw9ipM8Y', ''),
(716, 'Stephen Root & Steve Emney', 'Childish Games', 'Burnout', '2: Point of Impact', 'zyt1-AMsrgc', ''),
(717, 'Stephen Root & Steve Emney', 'Dark Moon Rising', 'Burnout', '2: Point of Impact', 'KWFkr0BcesE', ''),
(718, 'Stephen Root & Steve Emney', 'Credits', 'Burnout', '2: Point of Impact', 'BRoaaGUMwQs', ''),
(719, 'Stephen Root & Steve Emney', 'Theme', 'Burnout', '2: Point of Impact', 'Rj4r0FQLmvk', ''),
(720, 'Stephen Root & Steve Emney', 'Another World', 'Burnout', '3: Takedown', 'vmFit-ItJFg', 'Unreleased soundtrack due to EA Trax.'),
(721, 'Stephen Root & Steve Emney', 'Betty\'s Last Voyage', 'Burnout', '3: Takedown', 'hMAqsuQKS0I', 'Ending used when unlocking car. Unreleased soundtrack due to EA Trax. '),
(722, 'Stephen Root & Steve Emney', 'Liquid Sky', 'Burnout', '3: Takedown', 'jFAWcnuh3vo', 'Unreleased soundtrack due to EA Trax.'),
(723, 'Stephen Root & Steve Emney', 'Red Sky Horizon', 'Burnout', '3: Takedown', '0Vc-q5yPTs4', 'Unreleased soundtrack due to EA Trax.'),
(724, 'Stephen Root & Steve Emney', 'Shine', 'Burnout', '3: Takedown', '9IHbOsnA7To', 'Unreleased soundtrack due to EA Trax.'),
(725, 'Stephen Root & Steve Emney', 'Take Cover', 'Burnout', '3: Takedown', '7KJht_P9gtk', 'Unreleased soundtrack due to EA Trax.'),
(726, 'Stephen Root & Steve Emney', '16 Years On', 'Burnout', '3: Takedown', 'fggs9W4WVeQ', 'Unreleased soundtrack due to EA Trax.'),
(727, 'Stephen Root & Steve Emney', 'Ozone', 'Burnout', '3: Takedown', 'sAN3Gl4PbzQ', 'Title screen music. Unreleased soundtrack due to EA Trax.'),
(728, 'Stephen Root & Steve Emney', 'Tonight This Ends', 'Burnout', '3: Takedown', 'JYZWlQIcvvk', 'Unreleased soundtrack due to EA Trax.'),
(729, 'Guns N\' Roses', 'Paradise City', 'Burnout', 'Paradise', 'WJUInYShJYo', 'Guns N\' Roses Trailer; TV Ad. Official Reveal Trailer'),
(730, 'Brian Tyler', 'Need For Speed: The Run (all songs)', 'Need for Speed', 'The Run', 'ZclUYn_mNpw', ''),
(731, 'No Motiv', 'Independence Day', 'Burnout', '3: Takedown', 'ec1lYHHn7ps', 'Race training video.'),
(732, 'Amber Pacific', 'Always You', 'Burnout', '3: Takedown', '8A4TmtgF2Y8', ''),
(733, 'The Ordinary Boys', 'Over the Counter Culture', 'Burnout', '3: Takedown', 'GdgkuvsAI5I', ''),
(734, 'Funeral for a Friend', 'Rookie of the Year', 'Burnout', '3: Takedown', 'xuyLj9V-eNo', ''),
(735, 'Chronic Future', 'Time and Time Again', 'Burnout', '3: Takedown', 'g64xXt1Hb2w', ''),
(736, 'Franz Ferdinand', 'This Fire', 'Burnout', '3: Takedown', 'C3GbKbZLLto', 'Accolades Trailer'),
(737, 'The Von Bondies', 'C\'mon C\'mon', 'Burnout', '3: Takedown', 'VcPOGS5S28g', ''),
(738, 'Ramones', 'I Wanna Be Sedated', 'Burnout', '3: Takedown', '8O9P5Us_eVo', ''),
(739, 'Autopilot Off', 'Make a Sound', 'Burnout', '3: Takedown', 'BEDxHC3Kay8', ''),
(740, 'Ash', 'Orpheus', 'Burnout', '3: Takedown', 'znaW7gUKruM', 'TV Ad. Crash training video.'),
(741, 'Yellowcard', 'Breathing', 'Burnout', '3: Takedown', 'GOizClOIHWw', ''),
(742, 'Pennywise', 'Rise Up', 'Burnout', '3: Takedown', 'MHcQVcN1lVI', ''),
(743, 'Fall Out Boy', 'Reinventing the Wheel to Run Myself Over', 'Burnout', '3: Takedown', 'z4KUlV8RwBA', ''),
(744, 'The F-Ups', 'Lazy Generation', 'Burnout', '3: Takedown', 'zE4CpkcdEOQ', 'Intro. Trailer.'),
(745, 'The Lot Six', 'Autobrats', 'Burnout', '3: Takedown', 'n3_GTVsl9l0', ''),
(746, 'Sahara Hotnights', 'Hot Night Crash', 'Burnout', '3: Takedown', 'O_gcrm6Lsvo', ''),
(747, 'Eighteen Visions', 'I Let Go', 'Burnout', '3: Takedown', 'eK9AKbJeJTE', ''),
(748, 'Donots', 'Saccharine Smile', 'Burnout', '3: Takedown', 'hUAu-FtrVJI', ''),
(749, 'From First To Last', 'Populace in Two', 'Burnout', '3: Takedown', 'x_dMyFj7ppk', ''),
(750, 'Sugarcult', 'Memory', 'Burnout', '3: Takedown', '9n9MTqr9UNk', ''),
(751, 'Finger Eleven', 'Stay in Shadow', 'Burnout', '3: Takedown', '-X3JoVMrOrg', ''),
(752, 'Reggie and the Full Effect', 'Congratulations Smack And Katy', 'Burnout', '3: Takedown', 'b9CNSbJ-PLg', ''),
(753, 'Local H', 'Everyone Alive', 'Burnout', '3: Takedown', 'O1Y_dr10izk', ''),
(754, 'Maxeen', 'Please', 'Burnout', '3: Takedown', 'cY4CDi513bA', ''),
(755, 'New Found Glory', 'At Least I\'m Known for Something', 'Burnout', '3: Takedown', 'PtG-k7xCLcw', ''),
(756, 'My Chemical Romance', 'I\'m Not Okay (I Promise)', 'Burnout', '3: Takedown', 'NeeYLy2xwNg', ''),
(757, 'Go Betty Go', 'C\'mon', 'Burnout', '3: Takedown', '0lEPG6fZMog', ''),
(758, 'Moments in Grace', 'Broken Promises', 'Burnout', '3: Takedown', 'rqAzPNMwrbQ', ''),
(759, 'Midtown', 'Give It Up', 'Burnout', '3: Takedown', 'N6esbsx2ux8', ''),
(760, '1208', 'Fall Apart', 'Burnout', '3: Takedown', 'OsBiNiJ7H-s', ''),
(761, 'Motion City Soundtrack', 'My Favorite Accident', 'Burnout', '3: Takedown', 'tnV7F1tsmEQ', ''),
(762, 'Rise Against', 'Paper Wings', 'Burnout', '3: Takedown', '3qtirpRJ7j4', ''),
(763, 'The Bouncing Souls', 'Sing Along Forever', 'Burnout', '3: Takedown', 'AUFCqMpp2ag', ''),
(764, 'The Matches', 'Audio Blood', 'Burnout', '3: Takedown', '6vTBNNHbAC8', ''),
(765, 'Silent Drive', '4/16', 'Burnout', '3: Takedown', 'r5Yuq4CzkBA', ''),
(766, 'The Explosion', 'Here I Am', 'Burnout', '3: Takedown', '1ieRUaU5gmE', ''),
(767, 'The D4', 'Come On!', 'Burnout', '3: Takedown', 'gZJNXNrH92w', ''),
(768, 'The Mooney Suzuki', 'Shake That Bush Again', 'Burnout', '3: Takedown', '1nZjS534feo', ''),
(769, 'Mudmen', 'Animal', 'Burnout', '3: Takedown', 'YmNk91QRghI', ''),
(770, 'The Futureheads', 'Decent Days and Nights', 'Burnout', '3: Takedown', 'e9wrTVfyNIs', ''),
(771, 'Burning Brides', 'Heart Full Of Black', 'Burnout', '3: Takedown', 'Q3cid2uWt2o', ''),
(772, 'Atreyu', 'Right Side of the Bed', 'Burnout', '3: Takedown', '-qKjLJBoD3Q', ''),
(773, 'Letter Kills', 'Radio Up', 'Burnout', '3: Takedown', '54C-8CftRWU', ''),
(774, 'Jimmy Eat World', 'Just Tonight', 'Burnout', '3: Takedown', 'waUWipzd2A4', ''),
(775, 'Max﻿ Richter', 'Sarajevo', 'Need for Speed', 'The Movie', '-NazM23kl3Y', 'From #1 Trailer'),
(776, 'Yellowcard', 'Lights and Sounds', 'Burnout', 'Legends', 'Gx_hiRqOzpI', ''),
(777, 'The Outline', 'Shotgun', 'Burnout', 'Legends', 'HV7sRrCG9SE', 'PSP Trailer #1 '),
(778, 'Pennywise', 'Stand Up', 'Burnout', 'Legends', 'mpiJi_nX1uU', ''),
(779, 'Dogs', 'Tuned to a Different Station', 'Burnout', 'Legends', 'H0h1suV_l4Q', ''),
(780, 'OK Go', 'Do What You Want', 'Burnout', 'Legends', 'JdRbObigliA', ''),
(781, 'Tsar', 'Band - Girls - Money', 'Burnout', 'Legends', 'zHsTlEOsZxY', ''),
(782, 'The Academy Is...', 'Almost Here', 'Burnout', 'Legends', 'q4U1u6G1Ue4', ''),
(783, 'The Dead 60s', 'The Riot Radio', 'Burnout', 'Legends', 'iDSAiGTzNpA', ''),
(784, 'Morningwood', 'Nu Rock', 'Burnout', 'Legends', '2pGNa24g6RE', ''),
(785, 'Junkie XL', 'Today', 'Burnout', 'Legends', '9rZ9X_QvIlQ', ''),
(786, 'MxPx', 'Heard That Sound', 'Burnout', 'Legends', 'eCAfjhHz2J0', ''),
(787, 'Animal Alpha', 'Bundy', 'Burnout', 'Legends', 'VNCjXzR_w3Y', ''),
(788, 'Goldfinger', 'I Want', 'Burnout', 'Legends', 'by4Z8BHfVPk', ''),
(789, 'Finch', 'Ink', 'Burnout', 'Legends', 'HrZM0lik408', ''),
(790, 'Emanuel', 'The Hey Man', 'Burnout', 'Legends', 'ngPWvk5H6BQ', ''),
(791, 'Billy Talent', 'Red Flag', 'Burnout', 'Legends', 'ABUA8xCqgwU', ''),
(792, 'Comeback Kid', 'Wake The Dead', 'Burnout', 'Legends', '71w1Py1-wg4', ''),
(793, 'Mindless Self Indulgence', 'Straight To Video (KMFDM Remix)', 'Burnout', 'Legends', 'tdEiLj4B7lk', ''),
(794, 'We Are Scientists', 'The Great Escape', 'Burnout', 'Legends', 'VBgGf-chuIc', ''),
(795, 'The Black Velvets', 'Fear and Loathing', 'Burnout', 'Legends', 'AI73WHog3tk', ''),
(796, 'Nine Black Alps', 'Shot Down', 'Burnout', 'Legends', 'ke_jzz1v1AI', ''),
(797, 'Vanesa Lorena', 'Crash City', 'Burnout', 'Crash!', 'vcjIIkXXqaw', ''),
(798, 'Vanesa Lorena', 'Detonate Me', 'Burnout', 'Crash!', 'nR3Ow-3hgjQ', ''),
(799, 'Vanesa Lorena', 'Traffic Attack', 'Burnout', 'Crash!', '1gEALAw8kp4', ''),
(800, 'Vanesa Lorena', 'Piled Up', 'Burnout', 'Crash!', 'dvu_niXGqSc', 'New Official Gameplay Trailer'),
(801, 'The Primitives', 'Crash', 'Burnout', 'Crash!', 'eg6-CeCtGfo', ''),
(802, 'Vanilla Ice', 'Ice Ice Baby', 'Burnout', 'Crash!', 'rog8ou-ZepE', ''),
(803, 'Salt-n-Pepa', 'Push It', 'Burnout', 'Crash!', 'vCadcBR95oU', ''),
(804, 'Miami Sound Machine', 'Dr. Beat', 'Burnout', 'Crash!', 'bEWn0orWkMs', ''),
(805, 'The Weather Girls', 'It\'s Raining Men', 'Burnout', 'Crash!', '4x6leDGV7gs', ''),
(806, 'Inner Circle', 'Bad Boys', 'Burnout', 'Crash!', 'OSk5K-ijm5w', ''),
(807, 'Spandau Ballet', 'Gold', 'Burnout', 'Crash!', 'VQ4qrcHyYj4', ''),
(808, 'Dame Shirley Bassey', 'Big Spender (NorthxNWest Remix)', 'Burnout', 'Crash!', '42GJsGVy4To', ''),
(809, 'Giuseppe Verdi', 'Messa Da Requiem', 'Burnout', 'Crash!', 'ucG2KcDcViw', 'Trailer: Gamescom.'),
(810, 'Yellowcard', 'Lights and Sounds', 'Burnout', 'Revenge', 'Gx_hiRqOzpI', 'Xbox 360 Trailer.'),
(811, 'The Doors', 'Break on Through (BT vs The Doors Remix)', 'Burnout', 'Revenge', '-Y4jNjjQi5c', ''),
(812, 'The Outline', 'Shotgun', 'Burnout', 'Revenge', 'HV7sRrCG9SE', ''),
(813, 'Apocalyptica', 'Life Burns!', 'Burnout', 'Revenge', 'e82Te1Y4LVA', ''),
(814, 'The All-American Rejects', 'Top Of The World', 'Burnout', 'Revenge', 'SB9BO2lNp6g', ''),
(815, 'The Chemical Brothers', 'Big Jump', 'Burnout', 'Revenge', 'eSwA7yJkqX4', ''),
(816, 'Pennywise', 'Stand Up', 'Burnout', 'Revenge', 'mpiJi_nX1uU', ''),
(817, 'Dogs', 'Tuned to a Different Station', 'Burnout', 'Revenge', 'H0h1suV_l4Q', ''),
(818, 'The Starting Line', 'The World', 'Burnout', 'Revenge', '4n4l1PJWW_o', ''),
(819, 'LCD Soundsystem', 'Daft Punk is Playing At My House (Soulwax Shibuya Remix)', 'Burnout', 'Revenge', '9KlQZKJYG8U', ''),
(820, 'OK Go', 'Do What You Want', 'Burnout', 'Revenge', 'JdRbObigliA', ''),
(821, 'Tsar', 'Band - Girls - Money', 'Burnout', 'Revenge', 'zHsTlEOsZxY', ''),
(822, 'Andy Hunter', 'Come On', 'Burnout', 'Revenge', 'XdgtXsKlpCY', 'Cinematic Intro. PS2/Xbox Trailer.'),
(823, 'The Academy Is...', 'Almost Here', 'Burnout', 'Revenge', 'q4U1u6G1Ue4', ''),
(824, 'The Dead 60s', 'The Riot Radio', 'Burnout', 'Revenge', 'iDSAiGTzNpA', ''),
(825, 'Morningwood', 'Nu Rock', 'Burnout', 'Revenge', '2pGNa24g6RE', ''),
(826, 'Junkie XL', 'Today', 'Burnout', 'Revenge', '9rZ9X_QvIlQ', ''),
(827, 'MxPx', 'Heard That Sound', 'Burnout', 'Revenge', 'eCAfjhHz2J0', ''),
(828, 'Animal Alpha', 'Bundy', 'Burnout', 'Revenge', 'VNCjXzR_w3Y', ''),
(829, 'Goldfinger', 'I Want', 'Burnout', 'Revenge', 'by4Z8BHfVPk', ''),
(830, 'Bullet for My Valentine', 'Hand of Blood', 'Burnout', 'Revenge', 'X3GtCAOnnUc', ''),
(831, 'Fall Out Boy', 'Dance Dance', 'Burnout', 'Revenge', 'xAvpVg8LZuE', ''),
(832, 'Funeral for a Friend', 'All The Rage', 'Burnout', 'Revenge', '9jq4qIxLtEQ', ''),
(833, 'Maximo Park', 'Apply Some Pressure', 'Burnout', 'Revenge', 'nvof-V4PSvI', ''),
(834, 'Infusion', 'Better World (Freeland Remix)', 'Burnout', 'Revenge', 'L1ScAlojqUA', ''),
(835, 'The Bravery', 'An Honest Mistake (Superdiscount Remix)', 'Burnout', 'Revenge', 'tG8AoQFRDWw', ''),
(836, 'Finch', 'Ink', 'Burnout', 'Revenge', 'HrZM0lik408', ''),
(837, 'CKY', 'As The Tables Turn', 'Burnout', 'Revenge', 'Wo1-EjkqMeU', ''),
(838, 'Billy Talent', 'Red Flag', 'Burnout', 'Revenge', 'ABUA8xCqgwU', ''),
(839, 'Comeback Kid', 'Wake The Dead', 'Burnout', 'Revenge', '71w1Py1-wg4', ''),
(840, 'Bloc Party', 'Helicopter', 'Burnout', 'Revenge', 'yWAxTWXRncE', ''),
(841, 'Asian Dub Foundation', 'Flyover', 'Burnout', 'Revenge', 'tCEXIKRKynI', ''),
(842, 'Mindless Self Indulgence', 'Straight To Video (KMFDM Remix)', 'Burnout', 'Revenge', 'tdEiLj4B7lk', ''),
(843, 'Avenged Sevenfold', 'Beast (and the Harlot)', 'Burnout', 'Revenge', 'v85yLP2OqME', ''),
(844, 'Timo Maas', 'First Day (General Midi Remix)', 'Burnout', 'Revenge', 'Ip1I12xpwqg', ''),
(845, 'We Are Scientists', 'The Great Escape', 'Burnout', 'Revenge', 'VBgGf-chuIc', ''),
(846, 'Unwritten Law', 'F.I.G.H.T.', 'Burnout', 'Revenge', 'KCA55egtZwc', ''),
(847, 'The Black Velvets', 'Fear and Loathing', 'Burnout', 'Revenge', 'AI73WHog3tk', ''),
(848, 'Thrice', 'Lullaby', 'Burnout', 'Revenge', 'HXhrl-KIG50', ''),
(849, 'Nine Black Alps', 'Shot Down', 'Burnout', 'Revenge', 'ke_jzz1v1AI', ''),
(850, 'Emanuel', 'The Hey Man', 'Burnout', 'Revenge', 'ngPWvk5H6BQ', ''),
(851, '¡Forward Russia!', 'Nine', 'Burnout', 'Dominator', 'WAk7ztGI2zE', ''),
(852, 'Alice in Chains', 'Would?', 'Burnout', 'Dominator', 'fAfGjVUm1E8', ''),
(853, 'Army of Anyone', 'It Doesn\'t Seem To Matter', 'Burnout', 'Dominator', '1DHylnqxFGU', ''),
(854, 'Army of Me', 'Going Through Changes', 'Burnout', 'Dominator', 'LmFgU3MzhXw', ''),
(855, 'Avril Lavigne', 'Girlfriend', 'Burnout', 'Dominator', '6YSsti1MTgQ', ''),
(856, 'B\'z', 'Friction', 'Burnout', 'Dominator', 'Ug4QyKLhIDM', ''),
(857, 'Brand New', 'The Archers Bows Have Broken', 'Burnout', 'Dominator', 'd9nDXQ0KENM', ''),
(858, 'Bromheads Jacket', 'Fight Music For The Fight', 'Burnout', 'Dominator', '9E8pgvV11h8', ''),
(859, 'Dead Identities', 'Long Way Out', 'Burnout', 'Dominator', 'dhtJowheKjg', ''),
(860, 'Earl Greyhound', 'S.O.S.', 'Burnout', 'Dominator', 'hWQv1o1l4k8', ''),
(861, 'Filter', 'Hey Man Nice Shot (Big Mac Mix)', 'Burnout', 'Dominator', '9Vvo8imey8Y', ''),
(862, 'Hot Hot Heat', 'Give Up?', 'Burnout', 'Dominator', 'wd8_9gavaaI', ''),
(863, 'Jane\'s Addiction', 'Stop!', 'Burnout', 'Dominator', 'ZqCPU5wBrx4', ''),
(864, 'Killswitch Engage', 'My Curse', 'Burnout', 'Dominator', 'RuKmvkyOd1M', ''),
(865, 'LCD Soundsystem', 'Us V Them', 'Burnout', 'Dominator', 'rFjPT1WU0L0', ''),
(866, 'Lifetime', 'Haircuts and T-Shirts', 'Burnout', 'Dominator', 'NBvdI2ML2ww', ''),
(867, 'Make Good Your Escape', 'Beautiful Ruin', 'Burnout', 'Dominator', 'g9jyauZuT7w', ''),
(868, 'Maxeen', 'Block Out The World', 'Burnout', 'Dominator', 'ik5e7nRty8g', ''),
(869, 'N.E.R.D', 'Rockstar (Jason Nevins Remix)', 'Burnout', 'Dominator', 'oy7iN4e5qxA', ''),
(870, 'Saosin', 'Collapse', 'Burnout', 'Dominator', 'cuSWAuK6pKY', ''),
(871, 'Senses Fail', 'Calling All Cars', 'Burnout', 'Dominator', 'wXyDfT4KmGI', ''),
(872, 'Shadows Fall', 'Burning The Lives', 'Burnout', 'Dominator', '3KNunPVIQWc', ''),
(873, 'Shiny Toy Guns', 'Le Disko', 'Burnout', 'Dominator', 'pLq0PFEuMPk', ''),
(874, 'Skybombers', 'It Goes Off', 'Burnout', 'Dominator', 'UeMOmDS2KDk', ''),
(875, 'Sugarcult', 'Dead Living', 'Burnout', 'Dominator', '6q214wOVFvU', ''),
(876, 'The Confession', 'Through These Eyes', 'Burnout', 'Dominator', 'QE4hSwkPY5k', ''),
(877, 'The Fratellis', 'Chelsea Dagger', 'Burnout', 'Dominator', 'LBaxde247Mw', ''),
(878, 'The Have', 'One Step Ahead', 'Burnout', 'Dominator', 'oduKWWFFe4A', ''),
(879, 'The Photo Atlas', 'Red Orange Yellow', 'Burnout', 'Dominator', 'JQ66Kz5jMbw', ''),
(880, 'The Styles', 'Glitter Hits (J. J. Puig Mix)', 'Burnout', 'Dominator', 'YEXj5GEIHaw', ''),
(881, 'The Sword', 'Freya', 'Burnout', 'Dominator', 'Hr2m1VzTAI8', ''),
(882, 'Trivium', 'Anthem (We Are The Fire)', 'Burnout', 'Dominator', 'JWjeXQq3yzk', ''),
(883, 'Wired All Wrong', 'Lost Angeles', 'Burnout', 'Dominator', 'cxaDKzl-H50', ''),
(884, 'LCD Soundsystem', 'Us V Them', 'Burnout', 'Paradise', 'rFjPT1WU0L0', ''),
(885, 'Jane\'s Addiction', 'Stop!', 'Burnout', 'Paradise', '8ecc3gI1kmk', ''),
(886, 'Killswitch Engage', 'My Curse', 'Burnout', 'Paradise', 'rSv-vGFc3IA', 'Teaser Trailer '),
(887, 'Adam and the Ants', 'Stand And Deliver', 'Burnout', 'Paradise', 'OSOsx3E7JWk', ''),
(888, 'Alice in Chains', 'Would?', 'Burnout', 'Paradise', 'LhBUX1GPIvg', ''),
(889, 'Avril Lavigne', 'Girlfriend', 'Burnout', 'Paradise', 'KTiuB9CZSdw', ''),
(890, 'Brand New', 'Archers', 'Burnout', 'Paradise', 'WL2pHQBcujg', 'In-game: The Archers Bows Have Broken'),
(891, 'Bromheads Jacket', 'Fight Music For The Fight', 'Burnout', 'Paradise', '9E8pgvV11h8', ''),
(892, 'Depeche Mode', 'Route 66 (Beatmasters Mix)', 'Burnout', 'Paradise', 'IPrIxKxQZF8', ''),
(893, 'Army of Me', 'Going Through Changes', 'Burnout', 'Paradise', 'sua5nY_JHNo', ''),
(894, 'Faith No More', 'Epic', 'Burnout', 'Paradise', 'wf2n-7fpRS4', ''),
(895, 'Make Good Your Escape', 'Beautiful Ruin', 'Burnout', 'Paradise', 'g9jyauZuT7w', ''),
(896, 'Maxeen', 'Block Out The World', 'Burnout', 'Paradise', 'ik5e7nRty8g', ''),
(897, 'N.E.R.D', 'Rockstar (Jason Nevins Remix)', 'Burnout', 'Paradise', 'h2asjkf2NcU', ''),
(898, 'B\'z', 'Friction', 'Burnout', 'Paradise', 'Ug4QyKLhIDM', ''),
(899, 'Saosin', 'Collapse', 'Burnout', 'Paradise', 'dBdM5MEI6t0', ''),
(900, 'Senses Fail', 'Calling All Cars', 'Burnout', 'Paradise', 'ZGQHcrTI81Q', ''),
(901, 'Skybombers', 'It Goes Off', 'Burnout', 'Paradise', 'UeMOmDS2KDk', ''),
(902, 'Soundgarden', 'Rusty Cage', 'Burnout', 'Paradise', 'IJbLMhqur5k', ''),
(903, 'Sugarcult', 'Dead Living', 'Burnout', 'Paradise', '6q214wOVFvU', ''),
(904, 'Swervedriver', 'Duel', 'Burnout', 'Paradise', 'DC5qUeNeYh0', ''),
(905, 'RDGLDGRN', 'Lootin\' In London', 'Need for Speed', 'Rivals', '753Ow1BdcTM', 'Gameplay Progression & Pursuit Tech Feature Trailer; Unlocking: Aston Martin Vanquish'),
(906, 'The Styles', 'Glitter Hits (J. J. Puig Mix)', 'Burnout', 'Paradise', 'YEXj5GEIHaw', ''),
(907, 'The Photo Atlas', 'Red Orange Yellow', 'Burnout', 'Paradise', 'JQ66Kz5jMbw', ''),
(908, 'Twisted Sister', 'I Wanna Rock', 'Burnout', 'Paradise', '4THIIH81jxM', ''),
(909, 'Never Heard of It', 'Finger on The Trigger', 'Burnout', 'Paradise', '55s7vxHUaeU', 'Missing in remastered version.'),
(910, 'Showing Off to Thieves', 'Everyone Has Their Secrets', 'Burnout', 'Paradise', '6JN7h_LwxI8', 'Missing in remastered version.'),
(911, 'Seether', 'Fake It', 'Burnout', 'Paradise', 'hT8Y83KLmjY', ''),
(912, 'The Pigeon Detectives', 'I\'m Not Sorry', 'Burnout', 'Paradise', '3LztjvnXOKA', ''),
(913, 'Permanent Me', 'Until You Leave', 'Burnout', 'Paradise', 'tGT9gMHjUK4', ''),
(914, 'Operator', 'Nothing To Lose', 'Burnout', 'Paradise', 'B4ns4sjzGPQ', ''),
(915, 'Mexicolas', 'Come Clean', 'Burnout', 'Paradise', 'KPN_XjWi6Qs', ''),
(916, 'Kerli', 'Creepshow', 'Burnout', 'Paradise', 'XZ0Nty4Tp5o', ''),
(917, 'Junkie XL', 'Cities in Dust (feat. Lauren Rocket)', 'Burnout', 'Paradise', 'OKAODafH40Q', ''),
(918, 'Jupiter One', 'Fire Away', 'Burnout', 'Paradise', 'je5Pg58qfWs', ''),
(919, 'Jimmy Eat World', 'Electable (Give It Up)', 'Burnout', 'Paradise', '8QSEN6u5my0', ''),
(920, 'Innerpartysystem', 'Heart of Fire', 'Burnout', 'Paradise', 'E1rQb0ySAuU', ''),
(921, 'Brain Failure', 'Coming Down to Beijing', 'Burnout', 'Paradise', 'jmjnd0ZKfzk', ''),
(922, 'Airbourne', 'Too Much Too Young Too Fast', 'Burnout', 'Paradise', '-XUYT6XKVA8', ''),
(923, 'Agent Blue', 'Snowhill', 'Burnout', 'Paradise', 'aoysc8YZHTI', ''),
(924, 'Stephen Root & Steve Emney', 'Burnout 2002 Reprise', 'Burnout', 'Paradise', 'sfvlPZUoJX8', ''),
(925, 'Stephen Root & Steve Emney', 'Tokyo Nights', 'Burnout', 'Paradise', 'f399IE4a0j8', ''),
(926, 'Stephen Root & Steve Emney', 'Bulldozer Blues', 'Burnout', 'Paradise', 'RntEn8ir2-w', ''),
(927, 'Stephen Root & Steve Emney', 'Round and Rounder', 'Burnout', 'Paradise', 'BAr--VK3dNo', ''),
(928, 'Stephen Root & Steve Emney', 'Pass Me By', 'Burnout', 'Paradise', 'MBtsR2GIRps', ''),
(929, 'Stephen Root & Steve Emney', 'Panic Attack', 'Burnout', 'Paradise', 'Fo66Facjv2I', ''),
(930, 'Stephen Root & Steve Emney', 'Ozone', 'Burnout', 'Paradise', 'ascz6OHIsJI', ''),
(931, 'Stephen Root & Steve Emney', 'Lyon', 'Burnout', 'Paradise', 'LpqD5l32bKM', 'Carson GT Nighthawk '),
(932, 'Stephen Root & Steve Emney', 'Like My Shirt', 'Burnout', 'Paradise', '1UNVGz2eRkI', ''),
(933, 'Stephen Root & Steve Emney', 'Halfway to Dreaming', 'Burnout', 'Paradise', 'dz8dAlpabYc', ''),
(934, 'Stephen Root & Steve Emney', 'Free', 'Burnout', 'Paradise', 'fHVdwBZYwp4', ''),
(935, 'Stephen Root & Steve Emney', 'Fight or Flight', 'Burnout', 'Paradise', 'm2YOZVhCN34', ''),
(936, 'Stephen Root & Steve Emney', 'Exodus', 'Burnout', 'Paradise', 'lpJ070NBF8E', 'Hunter Manhattan Spirit '),
(937, 'Stephen Root & Steve Emney', 'Dark Moon Rising', 'Burnout', 'Paradise', '6mWMubD2jiE', ''),
(938, 'Stephen Root & Steve Emney', 'Childish Games', 'Burnout', 'Paradise', 'WRkGeDWPiWs', ''),
(939, 'Stephen Root & Steve Emney', 'Chicken George', 'Burnout', 'Paradise', '6PvRGaNuzfw', 'Hunter Calvary Bootlegger '),
(940, 'Stephen Root & Steve Emney', 'Caught On a Wire', 'Burnout', 'Paradise', 'v1HJZOAINnU', ''),
(941, 'Stephen Root & Steve Emney', 'Burnout Paradise Theme', 'Burnout', 'Paradise', 'pRmHqiTIcP8', 'The Ultimate Box Trailer HD; Ultimate Driving Playground; Carson GT; Montgomery Hawker; Carson Annihilator; Hunter Manhattan and other cars promos'),
(942, 'Stephen Root & Steve Emney', 'Destroyer Mix', 'Burnout', 'Paradise', '2B1ERnCjWjc', ''),
(943, 'Stephen Root & Steve Emney', 'Bridge The Gap', 'Burnout', 'Paradise', 'VQrFbQN1GOE', ''),
(944, 'Stephen Root & Steve Emney', 'Backlash', 'Burnout', 'Paradise', 'QhW4EahZRtc', ''),
(945, 'Stephen Root & Steve Emney', 'A Photograph', 'Burnout', 'Paradise', 'EcryvLMgmGg', ''),
(946, 'Stephen Root & Steve Emney', '16 Years On', 'Burnout', 'Paradise', 'iqHtRWFOJDs', 'Toy Car Collection Trailer'),
(947, 'Stephen Root & Steve Emney', 'Another World', 'Burnout', 'Paradise', 'moFwVlKoBqU', ''),
(948, 'Stephen Root & Steve Emney', 'Betty\'s Last Voyage', 'Burnout', 'Paradise', 't42n37V14iE', ''),
(949, 'Stephen Root & Steve Emney', 'Liquid Sky', 'Burnout', 'Paradise', 'dBk3es33DUA', 'Jansen P12 Special '),
(950, 'Stephen Root & Steve Emney', 'Red Sky Horizon', 'Burnout', 'Paradise', '_HxMQozmKM0', ''),
(951, 'Stephen Root & Steve Emney', 'Shine', 'Burnout', 'Paradise', '6VE2o1mpW0E', ''),
(952, 'Stephen Root & Steve Emney', 'Take Cover', 'Burnout', 'Paradise', 'MF4QR6VbAUc', ''),
(953, 'Stephen Root & Steve Emney', 'Tonight This Ends', 'Burnout', 'Paradise', '8gg8Z2PCYVI', ''),
(954, 'Johann Sebastian Bach', 'Air on the G String', 'Burnout', 'Paradise', 'IHUTzAIZopk', ''),
(955, 'Luigi Boccherini', 'Minuet', 'Burnout', 'Paradise', 'FsJ1KSgs3e0', ''),
(956, 'Wolfgang Mozart', 'Eine kleine Nachtmusik - 2nd Movement', 'Burnout', 'Paradise', 'KGMVknHE93U', ''),
(957, 'Leo Delibes', 'Flower Duet from Lachme', 'Burnout', 'Paradise', '4JlWhMo7HWc', ''),
(958, 'Pyotr Tchaikovsky', 'Nutcracker Ballet Suite - Dance Of The Mirlitons', 'Burnout', 'Paradise', 'SCuICkUqXK4', ''),
(959, 'Camille Saint-Saens', 'Carnival Of The Animals - The Aquarium', 'Burnout', 'Paradise', '2FAc3HmfoSY', ''),
(960, 'Wolfgang Mozart', 'Horn Concerto #4', 'Burnout', 'Paradise', 'pp2-jSGdzfU', ''),
(961, 'Pyotr Tchaikovsky', 'Sleeping Beauty Ballet Suite - Waltz', 'Burnout', 'Paradise', 'EAZk7KZ_nBc', ''),
(962, 'Giuseppe Verdi', 'Hebrew Slaves Nabucco', 'Burnout', 'Paradise', 'H_haJcx_Kr8', ''),
(963, 'Antonin Dvorak', 'Symphony #9 Largo', 'Burnout', 'Paradise', 'hAnV2B01PHs', ''),
(964, 'Claude Debussy', 'Clair De Lune', 'Burnout', 'Paradise', 'AlB4WnC1Pr0', ''),
(965, 'Ludwig van Beethoven', 'Moonlight Sonata - 1st Movement', 'Burnout', 'Paradise', 'dS_U1XK3068', ''),
(966, 'Wolfgang Mozart', 'Piano Concerto #21', 'Burnout', 'Paradise', 'PiYbN9MIjd0', ''),
(967, 'Georg Handel', 'Water Music Suite #1 - Air', 'Burnout', 'Paradise', '6CGYhmkPdj4', ''),
(968, 'Camille Saint-Saens', 'Carnival Of The Animals - The Swan', 'Burnout', 'Paradise', 'f29QtzREf6U', ''),
(969, 'Georges Bizet', 'Habanera Carmen', 'Burnout', 'Paradise', 'rYxTbGTqlu4', ''),
(970, 'Wolfgang Mozart', 'Horn Concerto #3 - 3rd Movement', 'Burnout', 'Paradise', 'XuimVp704OY', ''),
(971, 'Giuseppe Verdi', 'Triumphal March from Aida', 'Burnout', 'Paradise', 'mo14Sv7xeQM', ''),
(972, 'Georg Handel', 'Water Music - Suite #2 In D Major', 'Burnout', 'Paradise', '3b5mab7h5zs', ''),
(973, 'Antonio Vivaldi', 'The Four Seasons: Spring - 1st Movement', 'Burnout', 'Paradise', 'E8c6mwJm0_E', ''),
(974, 'Johannes Brahms', 'Hungarian-Dance #5', 'Burnout', 'Paradise', 'sE0RSIw20vc', ''),
(975, '30 Seconds to Mars', 'Conquistador', 'Need for Speed', 'Rivals', '4kCLie5COfs', 'AllDrive trailer.'),
(976, 'Garmiani', 'Rumble', 'Need for Speed', 'Rivals', 'woeWyn1bC1c', 'Jaguar DLC Pack; Movie Cars Pack '),
(977, 'RDGLDGRN', 'Double Dutch', 'Need for Speed', 'Rivals', 'bNEdCQWQRR4', ''),
(978, 'Linkin Park', 'Castle of Glass (M. Shinoda Remix)', 'Need for Speed', 'Rivals', '7MrwSwfQh-4', ''),
(979, 'Cole Plante', 'Howling (feat. Cameron The Public)', 'Need for Speed', 'Rivals', 'feX1xn3LU1k', ''),
(980, 'Soulwax', 'Any Minute Now', 'Need for Speed', 'Underground 2', 'YmH7_2h4_rs', ''),
(981, 'Gary Numan', 'I Am Dust', 'Need for Speed', 'Rivals', 'De73UfTC7kY', ''),
(982, 'Feed Me', 'Rat Trap', 'Need for Speed', 'Rivals', 'Iefx_l0gYn4', 'Unlocking: Lamborghini Veneno'),
(983, 'Walking Def', 'Let Me Show You (feat. Virus Syndicate)', 'Need for Speed', 'Rivals', 'w8V3DMYroSg', ''),
(984, 'Flux Pavilion', 'Steve French (feat. Steve Aoki)', 'Need for Speed', 'Rivals', 'S8Rv3PORJX0', ''),
(985, 'Madeon', 'Technicolor (Club Extended)', 'Need for Speed', 'Rivals', 'ckKoKKHLIMo', ''),
(986, 'Jeff Dyck', 'Ferrari F50', '', 'Need for Speed II', 'o7mOZp_1VbI', ''),
(987, 'Jeff Dyck', 'Ford Indigo', '', 'Need for Speed II', 'sKUFvQ5nhSI', ''),
(988, 'The Buzzhorn', 'Ordinary (Instrumental Remix)', 'Need for Speed', 'Hot Pursuit 2', '8YVzDXpDeBA', ''),
(989, 'Course of Nature', 'Wall of Shame (Instrumental Remix)', 'Need for Speed', 'Hot Pursuit 2', 'KnmwZII_iS8', ''),
(990, 'Pulse Ultra', 'Build Your Cages (Instrumental Remix)', 'Need for Speed', 'Hot Pursuit 2', 'ff2nW_LCF9Q', ''),
(991, 'Hot Action Cop', 'Fever For The Flava (Instrumental Remix)', 'Need for Speed', 'Hot Pursuit 2', '2ndCsc0lJKY', ''),
(992, 'Hot Action Cop', 'Goin\' Down On It (Instrumental Remix)', 'Need for Speed', 'Hot Pursuit 2', 'IBxdndOz5cw', ''),
(993, 'Uncle Kracker', 'Keep It Comin\' (Instrumental Remix)', 'Need for Speed', 'Hot Pursuit 2', 'HJtkMF1yQa8', ''),
(994, 'Bush', 'The People That We Love (Instrumental Remix)', 'Need for Speed', 'Hot Pursuit 2', '6WbP33xaYQQ', ''),
(995, 'Rush', 'One Little Victory (Instrumental Remix)', 'Need for Speed', 'Hot Pursuit 2', 'ijVsRF8b-04', ''),
(996, 'Hyper', 'Live Forever (feat. Shirt)', 'Need for Speed', 'Rivals', 'ouYTl01vfKM', ''),
(997, 'Marilyn Manson', 'Tainted Love', 'Need for Speed', 'Hot Pursuit (2010)', 'V0BcZnnaoWA', 'E3 Trailer.'),
(998, 'Helmut Kraft & Miss Brown', 'Veyron 1001', 'Need for Speed', 'Rivals', '1wn6n5lhEr8', ''),
(999, 'Tom Salta', 'Original Music Score', 'Need for Speed', 'Underground 2', 'Q0bCHmjp0fs', 'It was used in few trailers.'),
(1000, 'Bastille', 'Pompeii (Kat Krazy Remix)', 'Need for Speed', 'Rivals', 'hombU-pkGJM', 'Unlocking: Chevrolet Corvette Stingray & Porsche 911 GT3 & Lamborghini Gallardo LP 570-4 Superleggera Edizione Tecnica & Ferrari Enzo Ferrari'),
